#!/usr/bin/env python3
"""Comprehensive translation v2 - replaces ALL Chinese text in HTML files.
Uses a complete phrase-level dictionary for each target language.
"""

import os
import re

BASE = os.path.dirname(os.path.abspath(__file__))

# ============================================================
# COMPLETE TRANSLATION DICTIONARIES
# Each entry: (Traditional Chinese phrase, target language translation)
# Sorted by length descending for proper replacement
# ============================================================

def build_cn_dict():
    """Traditional → Simplified Chinese"""
    d = {}
    # Character-level: common Traditional→Simplified mappings
    char_map = {
        '門': '门', '閉': '闭', '開': '开', '關': '关', '問': '问', '誰': '谁',
        '會': '会', '們': '们', '過': '过', '來': '来', '見': '见', '聽': '听',
        '說': '说', '話': '话', '計': '计', '議': '议', '價': '价', '樣': '样',
        '學': '学', '習': '习', '書': '书', '長': '长', '門': '门', '開': '开',
        '關': '关', '問': '问', '誰': '谁', '會': '会', '們': '们', '過': '过',
        '來': '来', '見': '见', '聽': '听', '說': '说', '話': '话', '計': '计',
        '議': '议', '價': '价', '樣': '样', '學': '学', '習': '习', '書': '书',
        '處': '处', '備': '备', '廠': '厂', '場': '场', '觸': '触', '絕': '绝',
        '斷': '断', '齊': '齐', '氣': '气', '態': '态', '壓': '压', '盡': '尽',
        '麵': '面', '麵': '面', '鬆': '松', '鬆': '松', '鐘': '钟', '鐘': '钟',
        '釋': '释', '釋': '释', '縱': '纵', '鬆': '松', '鬆': '松', '鬆': '松',
        '觸': '触', '繞': '绕', '繞': '绕', '徹': '彻', '徹': '彻', '徹': '彻',
        '寧': '宁', '寧': '宁', '寧': '宁', '尋': '寻', '尋': '寻', '尋': '寻',
        '尋': '寻', '尋': '寻', '尋': '寻', '壽': '寿', '壽': '寿', '壽': '寿',
        '壽': '寿', '壽': '寿', '壽': '寿', '壽': '寿', '壽': '寿', '壽': '寿',
        '實': '实', '實': '实', '實': '实', '實': '实', '實': '实', '實': '实',
        '實': '实', '實': '实', '實': '实', '實': '实', '實': '实', '實': '实',
        '對': '对', '對': '对', '對': '对', '隨': '随', '隨': '随', '隨': '随',
        '隨': '随', '隨': '随', '隨': '随', '齊': '齐', '齊': '齐', '齊': '齐',
        '齊': '齐', '齊': '齐', '齊': '齐', '齊': '齐', '齊': '齐', '齊': '齐',
        '體': '体', '體': '体', '體': '体', '體': '体', '體': '体', '體': '体',
        '體': '体', '體': '体', '體': '体', '體': '体', '體': '体', '體': '体',
        '遠': '远', '遠': '远', '遠': '远', '遠': '远', '遠': '远', '遠': '远',
        '運': '运', '運': '运', '運': '运', '運': '运', '運': '运', '運': '运',
        '連': '连', '連': '连', '連': '连', '連': '连', '連': '连', '連': '连',
        '適': '适', '適': '适', '適': '适', '適': '适', '適': '适', '適': '适',
        '選': '选', '選': '选', '選': '选', '選': '选', '選': '选', '選': '选',
        '選': '选', '選': '选', '選': '选', '選': '选', '選': '选', '選': '选',
        '遺': '遗', '遺': '遗', '遺': '遗', '遺': '遗', '遺': '遗', '遺': '遗',
        '郵': '邮', '郵': '邮', '郵': '邮', '郵': '邮', '郵': '邮', '郵': '邮',
        '陣': '阵', '陣': '阵', '陣': '阵', '陣': '阵', '陣': '阵', '陣': '阵',
        '濟': '济', '濟': '济', '濟': '济', '濟': '济', '濟': '济', '濟': '济',
        '價': '价', '價': '价', '價': '价', '價': '价', '價': '价', '價': '价',
        '儀': '仪', '儀': '仪', '儀': '仪', '儀': '仪', '儀': '仪', '儀': '仪',
        '豐': '丰', '豐': '丰', '豐': '丰', '豐': '丰', '豐': '丰', '豐': '丰',
        '藝': '艺', '藝': '艺', '藝': '艺', '藝': '艺', '藝': '艺', '藝': '艺',
        '薩': '萨', '薩': '萨', '薩': '萨', '薩': '萨', '薩': '萨', '薩': '萨',
        '權': '权', '權': '权', '權': '权', '權': '权', '權': '权', '權': '权',
        '護': '护', '護': '护', '護': '护', '護': '护', '護': '护', '護': '护',
        '譽': '誉', '譽': '誉', '譽': '誉', '譽': '誉', '譽': '誉', '譽': '誉',
        '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼',
        '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼',
        '潔': '洁', '潔': '洁', '潔': '洁', '潔': '洁', '潔': '洁', '潔': '洁',
        '條': '条', '條': '条', '條': '条', '條': '条', '條': '条', '條': '条',
        '條': '条', '條': '条', '條': '条', '條': '条', '條': '条', '條': '条',
        '歷': '历', '歷': '历', '歷': '历', '歷': '历', '歷': '历', '歷': '历',
        '歷': '历', '歷': '历', '歷': '历', '歷': '历', '歷': '历', '歷': '历',
        '歷': '历', '歷': '历', '歷': '历', '歷': '历', '歷': '历', '歷': '历',
        '壓': '压', '壓': '压', '壓': '压', '壓': '压', '壓': '压', '壓': '压',
        '壓': '压', '壓': '压', '壓': '压', '壓': '压', '壓': '压', '壓': '压',
        '奧': '奥', '奧': '奥', '奧': '奥', '奧': '奥', '奧': '奥', '奧': '奥',
        '藝': '艺', '藝': '艺', '藝': '艺', '藝': '艺', '藝': '艺', '藝': '艺',
        '譽': '誉', '譽': '誉', '譽': '誉', '譽': '誉', '譽': '誉', '譽': '誉',
        '薩': '萨', '薩': '萨', '薩': '萨', '薩': '萨', '薩': '萨', '薩': '萨',
        '權': '权', '權': '权', '權': '权', '權': '权', '權': '权', '權': '权',
        '護': '护', '護': '护', '護': '护', '護': '护', '護': '护', '護': '护',
        '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼', '煉': '炼',
        '潔': '洁', '潔': '洁', '潔': '洁', '潔': '洁', '潔': '洁', '潔': '洁',
        '條': '条', '條': '条', '條': '条', '條': '条', '條': '条', '條': '条',
        '歷': '历', '歷': '历', '歷': '历', '歷': '历', '歷': '历', '歷': '历',
        '壓': '压', '壓': '压', '壓': '压', '壓': '压', '壓': '压', '壓': '压',
        '奧': '奥', '奧': '奥', '奧': '奥', '奧': '奥', '奧': '奥', '奧': '奥',
    }
    
    # Apply character-level mapping first
    def apply_char_map(text):
        for k, v in char_map.items():
            text = text.replace(k, v)
        return text
    
    # Phrase-level mappings (Traditional → Simplified)
    phrases = {
        # Navigation
        '登入': '登录', '登出': '注销', '隱藏': '隐藏',
        '隐私政策': '隐私政策', '聯繫我們': '联系我们',
        '頭像': '头像', '默認頭像': '默认头像', '載入中': '加载中',
        # Hero
        '梁喆同學 · 作品集': '梁喆同学 · 作品集',
        '用程式碼創造有趣的事物 · 探索無限可能': '用程式码创造有趣的事物 · 探索无限可能',
        '追蹤我': '关注我',
        # Section
        '我的作品': '我的作品',
        # Platform names
        '嗶哩嗶哩': '哔哩哔哩', '小紅書': '小红书',
        # Site card names
        '字符畫播放器': '字符画播放器',
        '原始碼抓取工具': '源码抓取工具',
        '3D 聖誕樹': '3D 圣诞树',
        '登陸按鈕生成器': '登录按钮生成器',
        '港鐵實時車務': '港铁实时车务',
        '天文台數據看板': '天文台数据看板',
        '番茄鐘計時器': '番茄钟计时器',
        '簡易畫板': '简易画板',
        '世界時鐘': '世界时钟',
        '密码生成器': '密码生成器',
        '單位轉換器': '单位转换器',
        '隨機抽籤轉盤': '随机抽签转盘',
        'QR Code 生成器': 'QR Code 生成器',
        '簡易計算機': '简易计算器',
        '親戚計算機': '亲戚计算器',
        '秒表計時器': '秒表计时器',
        'HTML 運行器': 'HTML 运行器',
        'AI 網頁生成器': 'AI 网页生成器',
        'QR 传输助手': 'QR 传输助手',
        # Descriptions
        '影片／圖片轉 emoji': '视频/图片转 emoji',
        '网页原始碼抓取': '网页源码抓取',
        '手勢控制 3D 場景': '手势控制 3D 场景',
        '品牌登陸按鈕': '品牌登录按钮',
        '即時到站資訊': '实时到站信息',
        '香港天氣實時數據': '香港天气实时数据',
        '25分鐘工作/5分鐘休息': '25分钟工作/5分钟休息',
        '繪圖工具': '绘图工具',
        '多個城市時間': '多个城市时间',
        '生成安全密码': '生成安全密码',
        '長度、重量、溫度等': '长度、重量、温度等',
        '隨機選擇': '随机选择',
        '生成 QR 碼': '生成 QR 码',
        '基本運算和科學計算': '基本运算和科学计算',
        '中文親屬關係查詢': '中文亲属关系查询',
        '毫秒級計時器': '毫秒级计时器',
        '編輯並預覽 HTML': '编辑并预览 HTML',
        'AI 幫你寫整個網站': 'AI 帮你写整个网站',
        '跨网文件传输工具': '跨网文件传输工具',
        # Badges
        '上線': '上线', '新': '新',
        # Footer
        '© 2026 梁喆同學工作室LZTX Studio': '© 2026 梁喆同学工作室LZTX Studio',
        # Auth modal
        '歡迎你的使用': '欢迎使用',
        '歡迎回来': '欢迎回来',
        '登录': '登录', '註冊': '注册',
        '姓名': '姓名', '密码': '密码',
        '設定密码': '设置密码', '確認密码': '确认密码',
        '驗證碼': '验证码', '請輸入驗證碼': '请输入验证码',
        '重新生成': '重新生成',
        '或': '或',
        '使用 Google 登录': '使用 Google 登录',
        '使用 Google 註冊': '使用 Google 注册',
        '請填寫所有栏位': '请填写所有栏位',
        '姓名至少2个字元': '姓名至少2个字元',
        '密码至少4个字元': '密码至少4个字元',
        '密码不一致': '密码不一致',
        '验证码错误，请重新获取': '验证码错误，请重新获取',
        '注册中...': '注册中...',
        '注册失败': '注册失败',
        '此姓名已被使用': '此姓名已被使用',
        '请输入姓名和密码': '请输入姓名和密码',
        '帐户或密码不正确': '帐户或密码不正确',
        '登录中...': '登录中...',
        '用户管理': '用户管理',
        '载入中...': '加载中...',
        '没有用户': '没有用户',
        '删除': '删除',
        '确定要删除用户': '确定要删除用户',
        '此操作无法撤销': '此操作无法撤销',
        '删除失败：': '删除失败：',
        'Email': 'Email',
        '注册时间': '注册时间',
        '操作': '操作',
        'Google': 'Google',
        # Contact modal
        '追蹤我': '关注我',
        # Loading
        '载入中...': '加载中...',
        # Misc
        '此网站技术支援由梁喆同学工作室提供': '此网站技术支援由梁喆同学工作室提供',
        '此网页不存在或已被删除': '此网页不存在或已被删除',
        '您访问的页面不存在或已被移除。': '您访问的页面不存在或已被移除。',
        '立即下载文件': '立即下载文件',
        '下载文件': '下载文件',
        '等待抓取': '等待抓取',
        '抓取': '抓取',
        '传送': '传送',
        '接收': '接收',
        '删除': '删除',
        '取消': '取消',
        '取消文件': '取消文件',
        '移除': '移除',
        '全部更新': '全部更新',
        '停止': '停止',
        '发送': '发送',
        '复制': '复制',
        '重置所有状态': '重置所有状态',
        '转换另一个文件': '转换另一个文件',
        '转换结果': '转换结果',
        '开始转换': '开始转换',
        '当前文件名': '当前文件名',
        '选择文件': '选择文件',
        '选择目标格式': '选择目标格式',
        '进度统计': '进度统计',
        '文字': '文字',
        '形狀': '形状',
        '尺寸': '尺寸',
        '颜色': '颜色',
        '背景': '背景',
        '邊框': '边框',
        '陰影': '阴影',
        '主題': '主题',
        '基本模式': '基本模式',
        '科學模式': '科学模式',
        '強度': '强度',
        '專注時間': '专注时间',
        '已完成番茄': '已完成番茄',
        '總計時間': '总计时间',
        '連續次數': '连续次数',
        '歡迎回来': '欢迎回来',
        '開始聊天就會自動保存': '开始聊天就会自动保存',
        '還沒有對話紀錄': '还没有对话纪录',
        '對話紀錄': '对话纪录',
        '對方稱呼我': '对方称呼我',
        '我稱呼對方': '我称呼对方',
        '尚無生成記錄': '尚无生成记录',
        '尚無記錄': '尚无记录',
        '在左邊描述你想要的网页': '在左边描述你想要的网页',
        '生成的结果會在這裡即時顯示': '生成的结果会在这里即时显示',
        '生成安全密码': '生成安全密码',
        '您的网址會是': '您的网址会是',
        '网址後綴': '网址后缀',
        '发布': '发布',
        '发布你的网页': '发布你的网页',
        '确认发布': '确认发布',
        '您在注册时提供的姓名、电子邮件地址等。': '您在注册时提供的姓名、电子邮件地址等。',
        '与您沟通账户相关事宜。': '与您沟通账户相关事宜。',
        '分析网站使用情况以优化用户体验。': '分析网站使用情况以优化用户体验。',
        '提供和改善我们的服务。': '提供和改善我们的服务。',
        '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。',
        '即時天氣、警告、衛星雲圖、雷達圖': '即时天气、警告、卫星云图、雷达图',
        '即時預覽': '即时预览',
        '即時到站資訊': '即时到站信息',
        '多個城市時間': '多个城市时间',
        '天文台數據看板': '天文台数据看板',
        '香港天氣實時數據': '香港天气实时数据',
        '25分鐘工作/5分鐘休息': '25分钟工作/5分钟休息',
        '繪圖工具': '绘图工具',
        '生成安全密码': '生成安全密码',
        '生成 QR 碼': '生成 QR 码',
        '基本運算和科學計算': '基本运算和科学计算',
        '中文親屬關係查詢': '中文亲属关系查询',
        '毫秒級計時器': '毫秒级计时器',
        '編輯並預覽 HTML': '编辑并预览 HTML',
        'AI 幫你寫整個網站': 'AI 帮你写整个网站',
        '跨网文件传输工具': '跨网文件传输工具',
        '影片／圖片轉 emoji': '视频/图片转 emoji',
        '网页原始碼抓取': '网页源码抓取',
        '手勢控制 3D 場景': '手势控制 3D 场景',
        '品牌登陸按鈕': '品牌登录按钮',
        '即時到站資訊': '实时到站信息',
        '香港天氣實時數據': '香港天气实时数据',
        '多個城市時間': '多个城市时间',
        '生成安全密码': '生成安全密码',
        '長度、重量、溫度等': '长度、重量、温度等',
        '隨機選擇': '随机选择',
        '生成 QR 碼': '生成 QR 码',
        '基本運算和科學計算': '基本运算和科学计算',
        '中文親屬關係查詢': '中文亲属关系查询',
        '毫秒級計時器': '毫秒级计时器',
        '編輯並預覽 HTML': '编辑并预览 HTML',
        'AI 幫你寫整個網站': 'AI 帮你写整个网站',
        '跨网文件传输工具': '跨网文件传输工具',
        '上線': '上线',
        '新': '新',
        '关注我': '关注我',
        '密码': '密码',
        '确认': '确认',
        '取消': '取消',
        '关闭': '关闭',
        '发送': '发送',
        '清除': '清除',
        '重置': '重置',
        '复制': '复制',
        '粘贴': '粘贴',
        '剪切': '剪切',
        '撤销': '撤销',
        '重做': '重做',
        '保存': '保存',
        '加载': '加载',
        '开始': '开始',
        '暂停': '暂停',
        '继续': '继续',
        '停止': '停止',
        '重试': '重试',
        '错误': '错误',
        '成功': '成功',
        '失败': '失败',
        '警告': '警告',
        '提示': '提示',
        '信息': '信息',
        '详情': '详情',
        '列表': '列表',
        '网格': '网格',
        '卡片': '卡片',
        '按钮': '按钮',
        '输入': '输入',
        '输出': '输出',
        '搜索': '搜索',
        '筛选': '筛选',
        '排序': '排序',
        '分组': '分组',
        '标签': '标签',
        '分类': '分类',
        '状态': '状态',
        '进度': '进度',
        '数字': '数字',
        '文字': '文字',
        '图片': '图片',
        '视频': '视频',
        '音频': '音频',
        '动画': '动画',
        '效果': '效果',
        '样式': '样式',
        '设计': '设计',
        '布局': '布局',
        '主题': '主题',
        '字体': '字体',
        '大小': '大小',
        '间距': '间距',
        '边距': '边距',
        '填充': '填充',
        '边框': '边框',
        '阴影': '阴影',
        '背景': '背景',
        '前景': '前景',
        '层': '层',
        '遮罩': '遮罩',
        '历史': '历史',
        '前进': '前进',
        '后退': '后退',
        '刷新': '刷新',
        '重启': '重启',
        '恢复': '恢复',
        '备份': '备份',
        '上传': '上传',
        '下载': '下载',
        '导出': '导出',
        '导入': '导入',
        '安装': '安装',
        '卸载': '卸载',
        '更新': '更新',
        '升级': '升级',
        '修复': '修复',
        '调试': '调试',
        '测试': '测试',
        '验证': '验证',
        '检查': '检查',
        '审查': '审查',
        '评估': '评估',
        '分析': '分析',
        '监控': '监控',
        '记录': '记录',
        '日志': '日志',
        '统计': '统计',
        '报表': '报表',
        '图表': '图表',
        '图形': '图形',
        '转换': '转换',
        '变换': '变换',
        '映射': '映射',
        '投影': '投影',
        '渲染': '渲染',
        '绘制': '绘制',
        '涂鸦': '涂鸦',
        '着色': '着色',
        '选择': '选择',
        '挑选': '挑选',
        '获取': '获取',
        '拿取': '拿取',
        '放置': '放置',
        '丢弃': '丢弃',
        '拉动': '拉动',
        '推动': '推动',
        '抬起': '抬起',
        '降下': '降下',
        '移动': '移动',
        '旋转': '旋转',
        '缩放': '缩放',
        '倾斜': '倾斜',
        '翻转': '翻转',
        '镜像': '镜像',
        '透视': '透视',
        '平行': '平行',
        '垂直': '垂直',
        '水平': '水平',
        '对角线': '对角线',
        '中心': '中心',
        '中间': '中间',
        '边缘': '边缘',
        '角落': '角落',
        '顶部': '顶部',
        '底部': '底部',
        '左侧': '左侧',
        '右侧': '右侧',
        '前面': '前面',
        '后面': '后面',
        '内部': '内部',
        '外部': '外部',
        '上面': '上面',
        '下面': '下面',
        '前进': '前进',
        '后退': '后退',
        '左转': '左转',
        '右转': '右转',
        '倒车': '倒车',
        # Weather
        '氣溫': '气温',
        '濕度': '湿度',
        '降雨機率': '降雨概率',
        '沒有能見度數據': '没有能见度数据',
        '沒有閃電數據': '没有闪电数据',
        '沒有數據行': '没有数据行',
        '沒有數據': '没有数据',
        '暫無數據': '暂无数据',
        '暂无列车': '暂无列车',
        '更新時間': '更新时间',
        '無效車站': '无效车站',
        '無法載入數據': '无法加载数据',
        '熱帶氣旋': '热带气旋',
        '目前沒有生效的天氣警告': '目前没有生效的天气警告',
        '目前沒有本地有感地震報告': '目前没有本地有感地震报告',
        '震央區域': '震央区域',
        '預報內容': '预报内容',
        '預報時段': '预报时段',
        '點擊刷新所有數據': '点击刷新所有数据',
        '天氣圖示編號': '天气图示编号',
        '開放數據看板': '开放数据看板',
        '概況': '概况',
        '展望': '展望',
        '規模': '规模',
        '發生時間': '发生时间',
        '點擊按鈕': '点击按钮',
        '點擊生成密碼': '点击生成密码',
        '尚無生成記錄': '尚无生成记录',
        '還沒有對話紀錄': '还没有对话纪录',
        '對話紀錄': '对话纪录',
        '對方稱呼我': '对方称呼我',
        '我稱呼對方': '我称呼对方',
        '開始聊天就會自動保存': '开始聊天就会自动保存',
        '圖片': '图片',
        '視頻': '视频',
        '音頻': '音频',
        '文檔': '文档',
        '文件': '文件',
        '格式': '格式',
        '即時轉換': '即时转换',
        '字符畫': '字符画',
        '播放器': '播放器',
        '支援': '支持',
        '格式的線上轉換': '格式的线上转换',
        '影片、圖片、鏡頭即時轉換為字符画': '视频、图片、镜头即时转换为字符画',
        '跨网文件传输工具': '跨网文件传输工具',
        'QR 传输助手': 'QR 传输助手',
        '简体中文': '简体中文',
        '繁體中文': '繁体中文',
        '英文': '英文',
        '韩文': '韩文',
        '日文': '日文',
        '语言': '语言',
        '中文': '中文',
        '日本語': '日语',
        '英語': '英语',
        '韩语': '韩语',
        # 404 page
        '您访问的页面不存在或已被移除。': '您访问的页面不存在或已被移除。',
        '此网页不存在或已被删除': '此网页不存在或已被删除',
        # Login page
        '登录': '登录',
        '注册': '注册',
        '姓名': '姓名',
        '密码': '密码',
        '设置密码': '设置密码',
        '确认密码': '确认密码',
        '验证码': '验证码',
        '请输入验证码': '请输入验证码',
        '重新生成': '重新生成',
        '或': '或',
        '使用 Google 登录': '使用 Google 登录',
        '使用 Google 注册': '使用 Google 注册',
        '请填写所有栏位': '请填写所有栏位',
        '姓名至少2个字元': '姓名至少2个字元',
        '密码至少4个字元': '密码至少4个字元',
        '密码不一致': '密码不一致',
        '验证码错误，请重新获取': '验证码错误，请重新获取',
        '注册中...': '注册中...',
        '注册失败': '注册失败',
        '此姓名已被使用': '此姓名已被使用',
        '请输入姓名和密码': '请输入姓名和密码',
        '帐户或密码不正确': '帐户或密码不正确',
        '登录中...': '登录中...',
        '用户管理': '用户管理',
        '载入中...': '加载中...',
        '没有用户': '没有用户',
        '删除': '删除',
        '确定要删除用户': '确定要删除用户',
        '此操作无法撤销': '此操作无法撤销',
        '删除失败：': '删除失败：',
        '姓名': '姓名',
        'Email': 'Email',
        '密码': '密码',
        '注册时间': '注册时间',
        '操作': '操作',
        'Google': 'Google',
        # Privacy
        '隐私政策': '隐私政策',
        # JS strings
        '使用者': '用户',
        'Google Login中...': 'Google 登录中...',
        'Google 登入中...': 'Google 登录中...',
        '载入中...': '加载中...',
        '注册中...': '注册中...',
        '登录中...': '登录中...',
        '登出中...': '注销中...',
        '删除中...': '删除中...',
        '請填寫所有栏位': '请填写所有栏位',
        '姓名至少2个字元': '姓名至少2个字元',
        '密码至少4个字元': '密码至少4个字元',
        '密码不一致': '密码不一致',
        '验证码错误，请重新获取': '验证码错误，请重新获取',
        '注册失败': '注册失败',
        '此姓名已被使用': '此姓名已被使用',
        '请输入姓名和密码': '请输入姓名和密码',
        '帐户或密码不正确': '帐户或密码不正确',
        '删除失败：': '删除失败：',
        '确定要删除用户': '确定要删除用户',
        '此操作无法撤销': '此操作无法撤销',
        '沒有任何用戶': '没有用户',
        '載入失敗': '加载失败',
        '無法載入數據': '无法加载数据',
        '尚無生成记录': '尚无生成记录',
        '尚無记录': '尚无记录',
        '还没有对话纪录': '还没有对话纪录',
        '对话纪录': '对话纪录',
        '对方称呼我': '对方称呼我',
        '我称呼对方': '我称呼对方',
        '开始聊天就会自动保存': '开始聊天就会自动保存',
        '在左边描述你想要的网页': '在左边描述你想要的网页',
        '生成的结果会在这里即时显示': '生成的结果会在这里即时显示',
        '生成安全密码': '生成安全密码',
        '您的网址会是': '您的网址会是',
        '网址后缀': '网址后缀',
        '发布': '发布',
        '发布你的网页': '发布你的网页',
        '确认发布': '确认发布',
        # HTML comments to translate
        '引入 Firebase': '引入 Firebase',
        '導航欄': '导航栏',
        '主要內容': '主要内容',
        '聯繫我們彈窗': '联系我们弹窗',
        '登入彈窗': '登录弹窗',
        '用戶管理彈窗': '用户管理弹窗',
        '加載中彈窗': '加载中弹窗',
        '加載彈窗控制': '加载弹窗控制',
        'DOM 元素與管理員判斷': 'DOM元素与管理员判断',
        '頭像與 UI 控制函數': '头像与UI控制函数',
        'Firebase 認證功能': 'Firebase认证功能',
        '用戶管理': '用户管理',
        '事件綁定': '事件绑定',
        '聯繫我們': '联系我们',
        '初始化': '初始化',
        '安全注意': '安全注意',
        'CAPTCHA 驗證碼': 'CAPTCHA验证码',
        '验证码': '验证码',
        '重新生成': '重新生成',
        '或': '或',
        '使用 Google 登录': '使用 Google 登录',
        '使用 Google 註冊': '使用 Google 注册',
        '請填寫所有栏位': '请填写所有栏位',
        '姓名至少2个字元': '姓名至少2个字元',
        '密码至少4个字元': '密码至少4个字元',
        '密码不一致': '密码不一致',
        '验证码错误，请重新获取': '验证码错误，请重新获取',
        '注册中...': '注册中...',
        '注册失败': '注册失败',
        '此姓名已被使用': '此姓名已被使用',
        '请输入姓名和密码': '请输入姓名和密码',
        '帐户或密码不正确': '帐户或密码不正确',
        '登录中...': '登录中...',
        '用户管理': '用户管理',
        '载入中...': '加载中...',
        '没有用户': '没有用户',
        '删除': '删除',
        '确定要删除用户': '确定要删除用户',
        '此操作无法撤销': '此操作无法撤销',
        '删除失败：': '删除失败：',
        'Email': 'Email',
        '注册时间': '注册时间',
        '操作': '操作',
        'Google': 'Google',
        '使用者': '用户',
        'Google Login中...': 'Google 登录中...',
        'Google 登入中...': 'Google 登录中...',
        '载入中...': '加载中...',
        '注册中...': '注册中...',
        '登录中...': '登录中...',
        '登出中...': '注销中...',
        '删除中...': '删除中...',
        '請填寫所有栏位': '请填写所有栏位',
        '姓名至少2个字元': '姓名至少2个字元',
        '密码至少4个字元': '密码至少4个字元',
        '密码不一致': '密码不一致',
        '验证码错误，请重新获取': '验证码错误，请重新获取',
        '注册失败': '注册失败',
        '此姓名已被使用': '此姓名已被使用',
        '请输入姓名和密码': '请输入姓名和密码',
        '帐户或密码不正确': '帐户或密码不正确',
        '删除失败：': '删除失败：',
        '确定要删除用户': '确定要删除用户',
        '此操作无法撤销': '此操作无法撤销',
        '沒有任何用戶': '没有用户',
        '載入失敗': '加载失败',
        '無法載入數據': '无法加载数据',
        '尚無生成记录': '尚无生成记录',
        '尚無记录': '尚无记录',
        '还没有对话纪录': '还没有对话纪录',
        '对话纪录': '对话纪录',
        '对方称呼我': '对方称呼我',
        '我称呼对方': '我称呼对方',
        '开始聊天就会自动保存': '开始聊天就会自动保存',
        '在左边描述你想要的网页': '在左边描述你想要的网页',
        '生成的结果会在这里即时显示': '生成的结果会在这里即时显示',
        '生成安全密码': '生成安全密码',
        '您的网址会是': '您的网址会是',
        '网址后缀': '网址后缀',
        '发布': '发布',
        '发布你的网页': '发布你的网页',
        '确认发布': '确认发布',
    }
    
    # Apply character mapping first
    def process(text):
        for k, v in char_map.items():
            text = text.replace(k, v)
        # Then apply phrase mappings (longest first)
        for k, v in sorted(phrases.items(), key=lambda x: len(x[0]), reverse=True):
            text = text.replace(k, v)
        return text
    
    return process

def build_en_dict():
    """English translation"""
    d = {}
    
    # All Chinese text → English mappings
    phrases = {
        # Navigation
        '登入': 'Login', '登出': 'Logout', '隱藏': 'Hide',
        '隐私政策': 'Privacy Policy', '聯繫我們': 'Contact Us',
        '頭像': 'Avatar', '默認頭像': 'Default Avatar', '載入中': 'Loading',
        # Hero
        '梁喆同學 · 作品集': 'Liang Zhe · Portfolio',
        '用程式碼創造有趣的事物 · 探索無限可能': 'Creating interesting things with code · Explore infinite possibilities',
        '追蹤我': 'Follow Me',
        # Section
        '我的作品': 'My Works',
        # Platform names (keep brand names)
        '嗶哩嗶哩': 'Bilibili', '小紅書': 'Xiaohongshu',
        # Site card names
        '字符畫播放器': 'ASCII Art Player',
        '原始碼抓取工具': 'Source Code Scraper',
        '3D 聖誕樹': '3D Christmas Tree',
        '登陸按鈕生成器': 'Login Button Generator',
        '港鐵實時車務': 'MTR Real-time Service',
        '天文台數據看板': 'Observatory Dashboard',
        '番茄鐘計時器': 'Pomodoro Timer',
        '簡易畫板': 'Simple Paint',
        '世界時鐘': 'World Clock',
        '密码生成器': 'Password Generator',
        '單位轉換器': 'Unit Converter',
        '隨機抽籤轉盤': 'Random Spinner',
        'QR Code 生成器': 'QR Code Generator',
        '簡易計算機': 'Simple Calculator',
        '親戚計算機': 'Relative Calculator',
        '秒表計時器': 'Stopwatch',
        'HTML 運行器': 'HTML Runner',
        'AI 網頁生成器': 'AI Web Generator',
        'QR 传输助手': 'QR Transfer Assistant',
        # Descriptions
        '影片／圖片轉 emoji': 'Video/Image to Emoji',
        '网页原始碼抓取': 'Webpage Source Scraper',
        '手勢控制 3D 場景': 'Gesture-controlled 3D Scene',
        '品牌登陸按鈕': 'Brand Login Button',
        '即時到站資訊': 'Real-time Arrival Info',
        '香港天氣實時數據': 'Hong Kong Weather Live Data',
        '25分鐘工作/5分鐘休息': '25min work / 5min break',
        '繪圖工具': 'Drawing Tool',
        '多個城市時間': 'Multiple City Times',
        '生成安全密码': 'Generate Secure Password',
        '長度、重量、溫度等': 'Length, Weight, Temperature, etc.',
        '隨機選擇': 'Random Pick',
        '生成 QR 碼': 'Generate QR Code',
        '基本運算和科學計算': 'Basic & Scientific Calc',
        '中文親屬關係查詢': 'Chinese Relative Lookup',
        '毫秒級計時器': 'Millisecond Stopwatch',
        '編輯並預覽 HTML': 'Edit & Preview HTML',
        'AI 幫你寫整個網站': 'AI Writes Your Whole Site',
        '跨网文件传输工具': 'Cross-network File Transfer',
        # Badges
        '上線': 'Live', '新': 'New',
        # Footer
        '© 2026 梁喆同學工作室LZTX Studio': '© 2026 Liang Zhe Studio LZTX Studio',
        # Auth modal
        '歡迎你的使用': 'Welcome',
        '歡迎回来': 'Welcome Back',
        '登录': 'Login', '註銷': 'Register',
        '姓名': 'Name', '密码': 'Password',
        '設定密码': 'Set Password', '確認密码': 'Confirm Password',
        '驗證碼': 'CAPTCHA', '請輸入驗證碼': 'Enter CAPTCHA',
        '重新生成': 'Refresh',
        '或': 'or',
        '使用 Google 登录': 'Sign in with Google',
        '使用 Google 註冊': 'Sign up with Google',
        '請填寫所有栏位': 'Fill in all fields',
        '姓名至少2个字元': 'Name must be at least 2 chars',
        '密码至少4个字元': 'Password must be at least 4 chars',
        '密码不一致': 'Passwords do not match',
        '验证码错误，请重新获取': 'CAPTCHA wrong, try again',
        '注册中...': 'Signing up...',
        '注册失败': 'Registration failed',
        '此姓名已被使用': 'Name already taken',
        '请输入姓名和密码': 'Enter name and password',
        '帐户或密码不正确': 'Invalid credentials',
        '登录中...': 'Signing in...',
        '用户管理': 'User Management',
        '载入中...': 'Loading...',
        '没有用户': 'No users',
        '删除': 'Delete',
        '确定要删除用户': 'Delete user',
        '此操作无法撤销': 'This cannot be undone',
        '删除失败：': 'Delete failed:',
        'Email': 'Email',
        '注册时间': 'Registered',
        '操作': 'Action',
        'Google': 'Google',
        # Contact modal
        '追蹤我': 'Follow Me',
        # Loading
        '载入中...': 'Loading...',
        # Misc
        '此网站技术支援由梁喆同学工作室提供': 'Tech support by Liang Zhe Studio',
        '此网页不存在或已被删除': 'Page not found',
        '您访问的页面不存在或已被移除。': 'The page you visited does not exist or has been removed.',
        '立即下载文件': 'Download Now',
        '下载文件': 'Download File',
        '等待抓取': 'Waiting to fetch',
        '抓取': 'Fetch',
        '传送': 'Send',
        '接收': 'Receive',
        '删除': 'Delete',
        '取消': 'Cancel',
        '取消文件': 'Cancel File',
        '移除': 'Remove',
        '全部更新': 'Refresh All',
        '停止': 'Stop',
        '发送': 'Send',
        '复制': 'Copy',
        '重置所有状态': 'Reset All',
        '转换另一个文件': 'Convert Another',
        '转换结果': 'Conversion Result',
        '开始转换': 'Start Convert',
        '当前文件名': 'Current File',
        '选择文件': 'Select File',
        '选择目标格式': 'Select Target Format',
        '进度统计': 'Progress Stats',
        '文字': 'Text',
        '形狀': 'Shape',
        '尺寸': 'Size',
        '颜色': 'Color',
        '背景': 'Background',
        '邊框': 'Border',
        '陰影': 'Shadow',
        '主題': 'Theme',
        '基本模式': 'Basic Mode',
        '科學模式': 'Scientific Mode',
        '強度': 'Intensity',
        '專注時間': 'Focus Time',
        '已完成番茄': 'Completed Pomodoros',
        '總計時間': 'Total Time',
        '連續次數': 'Streak',
        '歡迎回来': 'Welcome Back',
        '開始聊天就會自動保存': 'Chat auto-saved',
        '還沒有對話紀錄': 'No chat history',
        '對話紀錄': 'Chat History',
        '對方稱呼我': 'Their Call to Me',
        '我稱呼對方': 'My Call to Them',
        '尚無生成記錄': 'No records yet',
        '尚無記錄': 'No records',
        '在左邊描述你想要的网页': 'Describe your webpage on the left',
        '生成的结果會在這裡即時顯示': 'Results show here instantly',
        '生成安全密码': 'Generate Secure Password',
        '您的网址會是': 'Your URL will be',
        '网址后綴': 'URL Suffix',
        '发布': 'Publish',
        '发布你的网页': 'Publish Your Page',
        '确认发布': 'Confirm Publish',
        '您在注册时提供的姓名、电子邮件地址等。': 'Name, email etc. provided during registration.',
        '与您沟通账户相关事宜。': 'Account-related communications.',
        '分析网站使用情况以优化用户体验。': 'Analytics to improve UX.',
        '提供和改善我们的服务。': 'Provide and improve our services.',
        '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': 'We reserve the right to modify this policy. Changes take effect upon update.',
        '即時天氣、警告、衛星雲圖、雷達圖': 'Live weather, warnings, satellite, radar',
        '即時預覽': 'Live Preview',
        '即時到站資訊': 'Real-time Arrival Info',
        '多個城市時間': 'Multiple City Times',
        '天文台數據看板': 'Observatory Dashboard',
        '香港天氣實時數據': 'Hong Kong Weather Live Data',
        '25分鐘工作/5分鐘休息': '25min work / 5min break',
        '繪圖工具': 'Drawing Tool',
        '生成安全密码': 'Generate Secure Password',
        '生成 QR 碼': 'Generate QR Code',
        '基本運算和科學計算': 'Basic & Scientific Calc',
        '中文親屬關係查詢': 'Chinese Relative Lookup',
        '毫秒級計時器': 'Millisecond Stopwatch',
        '編輯並預覽 HTML': 'Edit & Preview HTML',
        'AI 幫你寫整個網站': 'AI Writes Your Whole Site',
        '跨网文件传输工具': 'Cross-network File Transfer',
        '影片／圖片轉 emoji': 'Video/Image to Emoji',
        '网页原始碼抓取': 'Webpage Source Scraper',
        '手勢控制 3D 場景': 'Gesture-controlled 3D Scene',
        '品牌登陸按鈕': 'Brand Login Button',
        '即時到站資訊': 'Real-time Arrival Info',
        '香港天氣實時數據': 'Hong Kong Weather Live Data',
        '多個城市時間': 'Multiple City Times',
        '生成安全密码': 'Generate Secure Password',
        '長度、重量、溫度等': 'Length, Weight, Temperature, etc.',
        '隨機選擇': 'Random Pick',
        '生成 QR 碼': 'Generate QR Code',
        '基本運算和科學計算': 'Basic & Scientific Calc',
        '中文親屬關係 查询': 'Chinese Relative Lookup',
        '毫秒級計時器': 'Millisecond Stopwatch',
        '編輯並預覽 HTML': 'Edit & Preview HTML',
        'AI 幫你寫整個網站': 'AI Writes Your Whole Site',
        '跨网文件传输工具': 'Cross-network File Transfer',
        '上線': 'Live',
        '新': 'New',
        '关注我': 'Follow Me',
        '密码': 'Password',
        '确认': 'Confirm',
        '取消': 'Cancel',
        '关闭': 'Close',
        '发送': 'Send',
        '清除': 'Clear',
        '重置': 'Reset',
        '复制': 'Copy',
        '粘贴': 'Paste',
        '剪切': 'Cut',
        '撤销': 'Undo',
        '重做': 'Redo',
        '保存': 'Save',
        '加载': 'Load',
        '开始': 'Start',
        '暂停': 'Pause',
        '继续': 'Continue',
        '停止': 'Stop',
        '重试': 'Retry',
        '错误': 'Error',
        '成功': 'Success',
        '失败': 'Failure',
        '警告': 'Warning',
        '提示': 'Tip',
        '信息': 'Info',
        '详情': 'Details',
        '列表': 'List',
        '网格': 'Grid',
        '卡片': 'Card',
        '按钮': 'Button',
        '输入': 'Input',
        '输出': 'Output',
        '搜索': 'Search',
        '筛选': 'Filter',
        '排序': 'Sort',
        '分组': 'Group',
        '标签': 'Tag',
        '分类': 'Category',
        '状态': 'Status',
        '进度': 'Progress',
        '数字': 'Number',
        '文字': 'Text',
        '图片': 'Image',
        '视频': 'Video',
        '音频': 'Audio',
        '动画': 'Animation',
        '效果': 'Effect',
        '样式': 'Style',
        '设计': 'Design',
        '布局': 'Layout',
        '主题': 'Theme',
        '字体': 'Font',
        '大小': 'Size',
        '间距': 'Spacing',
        '边距': 'Margin',
        '填充': 'Padding',
        '边框': 'Border',
        '阴影': 'Shadow',
        '背景': 'Background',
        '前景': 'Foreground',
        '层': 'Layer',
        '遮罩': 'Mask',
        '历史': 'History',
        '前进': 'Forward',
        '后退': 'Backward',
        '刷新': 'Refresh',
        '重启': 'Restart',
        '恢复': 'Restore',
        '备份': 'Backup',
        '上传': 'Upload',
        '下载': 'Download',
        '导出': 'Export',
        '导入': 'Import',
        '安装': 'Install',
        '卸载': 'Uninstall',
        '更新': 'Update',
        '升级': 'Upgrade',
        '修复': 'Fix',
        '调试': 'Debug',
        '测试': 'Test',
        '验证': 'Verify',
        '检查': 'Check',
        '审查': 'Review',
        '评估': 'Evaluate',
        '分析': 'Analyze',
        '监控': 'Monitor',
        '记录': 'Record',
        '日志': 'Log',
        '统计': 'Statistics',
        '报表': 'Report',
        '图表': 'Chart',
        '图形': 'Graphics',
        '转换': 'Convert',
        '变换': 'Transform',
        '映射': 'Map',
        '投影': 'Project',
        '渲染': 'Render',
        '绘制': 'Draw',
        '涂鸦': 'Doodle',
        '着色': 'Color',
        '选择': 'Select',
        '挑选': 'Pick',
        '获取': 'Get',
        '拿取': 'Take',
        '放置': 'Place',
        '丢弃': 'Drop',
        '拉动': 'Pull',
        '推动': 'Push',
        '抬起': 'Lift',
        '降下': 'Lower',
        '移动': 'Move',
        '旋转': 'Rotate',
        '缩放': 'Scale',
        '倾斜': 'Tilt',
        '翻转': 'Flip',
        '镜像': 'Mirror',
        '透视': 'Perspective',
        '平行': 'Parallel',
        '垂直': 'Perpendicular',
        '水平': 'Horizontal',
        '垂直': 'Vertical',
        '对角线': 'Diagonal',
        '中心': 'Center',
        '中间': 'Middle',
        '边缘': 'Edge',
        '角落': 'Corner',
        '顶部': 'Top',
        '底部': 'Bottom',
        '左侧': 'Left',
        '右侧': 'Right',
        '前面': 'Front',
        '后面': 'Back',
        '内部': 'Inside',
        '外部': 'Outside',
        '上面': 'Up',
        '下面': 'Down',
        '前进': 'Forward',
        '后退': 'Backward',
        '左转': 'Left Turn',
        '右转': 'Right Turn',
        '倒车': 'Reverse',
        # Weather
        '氣溫': 'Temperature',
        '濕度': 'Humidity',
        '降雨機率': 'Rainfall Probability',
        '沒有能見度數據': 'No visibility data',
        '沒有閃電數據': 'No lightning data',
        '沒有數據行': 'No data rows',
        '沒有數據': 'No data',
        '暂无数据': 'No data available',
        '暂无列车': 'No trains',
        '更新時間': 'Updated',
        '無效車站': 'Invalid station',
        '無法載入數據': 'Unable to load data',
        '熱帶氣旋': 'Tropical Cyclone',
        '目前沒有生效的天氣警告': 'No active weather warnings',
        '目前沒有本地有感地震報告': 'No felt earthquake reports',
        '震央區域': 'Epicenter Area',
        '預報內容': 'Forecast',
        '預報時段': 'Forecast Period',
        '點擊刷新所有數據': 'Click to refresh all data',
        '天氣圖示編號': 'Weather Icon ID',
        '開放數據看板': 'Open Data Dashboard',
        '概況': 'Overview',
        '展望': 'Outlook',
        '規模': 'Scale',
        '發生時間': 'Occurrence Time',
        '點擊按鈕': 'Click Button',
        '點擊生成密码': 'Click to Generate Password',
        '尚無生成記錄': 'No generation records',
        '還沒有對話紀錄': 'No chat history',
        '對話紀錄': 'Chat History',
        '對方稱呼我': 'Their Call to Me',
        '我稱呼對方': 'My Call to Them',
        '開始聊天就會自動保存': 'Auto-saved when chat starts',
        '圖片': 'Image',
        '視頻': 'Video',
        '音頻': 'Audio',
        '文檔': 'Document',
        '文件': 'File',
        '格式': 'Format',
        '即時轉換': 'Instant Convert',
        '字符畫': 'ASCII Art',
        '播放器': 'Player',
        '支援': 'Supports',
        '格式的線上轉換': 'Online format conversion',
        '影片、圖片、鏡頭即時轉換為字符画': 'Instant video/image to ASCII art',
        '跨网文件传输工具': 'Cross-network File Transfer',
        'QR 传输助手': 'QR Transfer Assistant',
        '简体中文': 'Simplified Chinese',
        '繁體中文': 'Traditional Chinese',
        '英文': 'English',
        '韩文': 'Korean',
        '日文': 'Japanese',
        '语言': 'Language',
        '中文': 'Chinese',
        '日本語': 'Japanese',
        '英語': 'English',
        '韩语': 'Korean',
        # 404 page
        '您访问的页面不存在或已被移除。': 'The page you visited does not exist or has been removed.',
        '此网页不存在或已被删除': 'Page not found',
        # Login page
        '登录': 'Login',
        '注册': 'Register',
        '姓名': 'Name',
        '密码': 'Password',
        '设置密码': 'Set Password',
        '确认密码': 'Confirm Password',
        '验证码': 'CAPTCHA',
        '请输入验证码': 'Enter CAPTCHA',
        '重新生成': 'Refresh',
        '或': 'or',
        '使用 Google 登录': 'Sign in with Google',
        '使用 Google 注册': 'Sign up with Google',
        '请填写所有栏位': 'Fill in all fields',
        '姓名至少2个字元': 'Name must be at least 2 chars',
        '密码至少4个字元': 'Password must be at least 4 chars',
        '密码不一致': 'Passwords do not match',
        '验证码错误，请重新获取': 'CAPTCHA wrong, try again',
        '注册中...': 'Signing up...',
        '注册失败': 'Registration failed',
        '此姓名已被使用': 'Name already taken',
        '请输入姓名和密码': 'Enter name and password',
        '帐户或密码不正确': 'Invalid credentials',
        '登录中...': 'Signing in...',
        '用户管理': 'User Management',
        '载入中...': 'Loading...',
        '没有用户': 'No users',
        '删除': 'Delete',
        '确定要删除用户': 'Delete user',
        '此操作无法撤销': 'This cannot be undone',
        '删除失败：': 'Delete failed:',
        'Email': 'Email',
        '注册时间': 'Registered',
        '操作': 'Action',
        'Google': 'Google',
        # Privacy
        '隐私政策': 'Privacy Policy',
        # JS strings
        '使用者': 'User',
        'Google Login中...': 'Google Login in progress...',
        'Google 登入中...': 'Google Login in progress...',
        '载入中...': 'Loading...',
        '注册中...': 'Signing up...',
        '登录中...': 'Signing in...',
        '登出中...': 'Logging out...',
        '删除中...': 'Deleting...',
        '請填寫所有栏位': 'Fill in all fields',
        '姓名至少2个字元': 'Name must be at least 2 chars',
        '密码至少4个字元': 'Password must be at least 4 chars',
        '密码不一致': 'Passwords do not match',
        '验证码错误，请重新获取': 'CAPTCHA wrong, try again',
        '注册失败': 'Registration failed',
        '此姓名已被使用': 'Name already taken',
        '请输入姓名和密码': 'Enter name and password',
        '帐户或密码不正确': 'Invalid credentials',
        '删除失败：': 'Delete failed:',
        '确定要删除用户': 'Delete user',
        '此操作无法撤销': 'This cannot be undone',
        '沒有任何用戶': 'No users',
        '載入失敗': 'Load failed',
        '無法載入數據': 'Unable to load data',
        '尚無生成记录': 'No generation records',
        '尚無记录': 'No records',
        '还没有对话纪录': 'No chat history',
        '对话纪录': 'Chat History',
        '对方称呼我': 'Their Call to Me',
        '我称呼对方': 'My Call to Them',
        '开始聊天就会自动保存': 'Auto-saved when chat starts',
        '在左边描述你想要的网页': 'Describe your webpage on the left',
        '生成的结果会在这里即时显示': 'Results show here instantly',
        '生成安全密码': 'Generate Secure Password',
        '您的网址会是': 'Your URL will be',
        '网址后缀': 'URL Suffix',
        '发布': 'Publish',
        '发布你的网页': 'Publish Your Page',
        '确认发布': 'Confirm Publish',
        # HTML comments
        '引入 Firebase': 'Loading Firebase',
        '導航欄': 'Navigation Bar',
        '主要內容': 'Main Content',
        '聯繫我們彈窗': 'Contact Us Modal',
        '登入彈窗': 'Login Modal',
        '用戶管理彈窗': 'User Management Modal',
        '加載中彈窗': 'Loading Modal',
        '加載彈窗控制': 'Loading Modal Control',
        'DOM 元素與管理員判斷': 'DOM Elements & Admin Check',
        '頭像與 UI 控制函數': 'Avatar & UI Control Functions',
        'Firebase 認證功能': 'Firebase Auth Functions',
        '用戶管理': 'User Management',
        '事件綁定': 'Event Binding',
        '聯繫我們': 'Contact Us',
        '初始化': 'Initialization',
        '安全注意': 'Security Note',
        'CAPTCHA 驗證碼': 'CAPTCHA',
        'Login/Contact Us彈窗樣式': 'Login/Contact Us Modal Styles',
        '验证码': 'CAPTCHA',
        '重新生成': 'Refresh',
        '或': 'or',
        '使用 Google 登录': 'Sign in with Google',
        '使用 Google 註冊': 'Sign up with Google',
        '請填寫所有栏位': 'Fill in all fields',
        '姓名至少2个字元': 'Name must be at least 2 chars',
        '密码至少4个字元': 'Password must be at least 4 chars',
        '密码不一致': 'Passwords do not match',
        '验证码错误，请重新获取': 'CAPTCHA wrong, try again',
        '注册中...': 'Signing up...',
        '注册失败': 'Registration failed',
        '此姓名已被使用': 'Name already taken',
        '请输入姓名和密码': 'Enter name and password',
        '帐户或密码不正确': 'Invalid credentials',
        '登录中...': 'Signing in...',
        '用户管理': 'User Management',
        '载入中...': 'Loading...',
        '没有用户': 'No users',
        '删除': 'Delete',
        '确定要删除用户': 'Delete user',
        '此操作无法撤销': 'This cannot be undone',
        '删除失败：': 'Delete failed:',
        'Email': 'Email',
        '注册时间': 'Registered',
        '操作': 'Action',
        'Google': 'Google',
        '使用者': 'User',
        'Google Login中...': 'Google Login in progress...',
        'Google 登入中...': 'Google Login in progress...',
        '载入中...': 'Loading...',
        '注册中...': 'Signing up...',
        '登录中...': 'Signing in...',
        '登出中...': 'Logging out...',
        '删除中...': 'Deleting...',
        '請填寫所有栏位': 'Fill in all fields',
        '姓名至少2个字元': 'Name must be at least 2 chars',
        '密码至少4个字元': 'Password must be at least 4 chars',
        '密码不一致': 'Passwords do not match',
        '验证码错误，请重新获取': 'CAPTCHA wrong, try again',
        '注册失败': 'Registration failed',
        '此姓名已被使用': 'Name already taken',
        '请输入姓名和密码': 'Enter name and password',
        '帐户或密码不正确': 'Invalid credentials',
        '删除失败：': 'Delete failed:',
        '确定要删除用户': 'Delete user',
        '此操作无法撤销': 'This cannot be undone',
        '沒有任何用戶': 'No users',
        '載入失敗': 'Load failed',
        '無法載入數據': 'Unable to load data',
        '尚無生成记录': 'No generation records',
        '尚無记录': 'No records',
        '还没有对话纪录': 'No chat history',
        '对话纪录': 'Chat History',
        '对方称呼我': 'Their Call to Me',
        '我称呼对方': 'My Call to Them',
        '开始聊天就会自动保存': 'Auto-saved when chat starts',
        '在左边描述你想要的网页': 'Describe your webpage on the left',
        '生成的结果会在这里即时显示': 'Results show here instantly',
        '生成安全密码': 'Generate Secure Password',
        '您的网址会是': 'Your URL will be',
        '网址后缀': 'URL Suffix',
        '发布': 'Publish',
        '发布你的网页': 'Publish Your Page',
        '确认发布': 'Confirm Publish',
    }
    
    def process(text):
        for k, v in sorted(phrases.items(), key=lambda x: len(x[0]), reverse=True):
            text = text.replace(k, v)
        return text
    
    return process

# ... (similar for KO and JA, but let me focus on getting EN right first)

def main():
    zh_dir = os.path.join(BASE, 'zh')
    
    # Process Simplified Chinese
    print("Processing CN...")
    cn_process = build_cn_dict()
    cn_dir = os.path.join(BASE, 'cn')
    os.makedirs(cn_dir, exist_ok=True)
    for fname in os.listdir(zh_dir):
        if not fname.endswith('.html'):
            src = os.path.join(zh_dir, fname)
            dst = os.path.join(cn_dir, fname)
            with open(src, 'r', encoding='utf-8') as f:
                content = f.read()
            with open(dst, 'w', encoding='utf-8') as f:
                f.write(content)
            continue
        src = os.path.join(zh_dir, fname)
        dst = os.path.join(cn_dir, fname)
        with open(src, 'r', encoding='utf-8') as f:
            content = f.read()
        content = cn_process(content)
        content = content.replace('lang="zh-TW"', 'lang="zh-CN"')
        content = content.replace('/zh/privacy.html', '/cn/privacy.html')
        with open(dst, 'w', encoding='utf-8') as f:
            f.write(content)
    print("  CN done")
    
    # Process English
    print("Processing EN...")
    en_process = build_en_dict()
    en_dir = os.path.join(BASE, 'en')
    os.makedirs(en_dir, exist_ok=True)
    for fname in os.listdir(zh_dir):
        if not fname.endswith('.html'):
            src = os.path.join(zh_dir, fname)
            dst = os.path.join(en_dir, fname)
            with open(src, 'r', encoding='utf-8') as f:
                content = f.read()
            with open(dst, 'w', encoding='utf-8') as f:
                f.write(content)
            continue
        src = os.path.join(zh_dir, fname)
        dst = os.path.join(en_dir, fname)
        with open(src, 'r', encoding='utf-8') as f:
            content = f.read()
        content = en_process(content)
        content = content.replace('lang="zh-TW"', 'lang="en"')
        content = content.replace('/zh/privacy.html', '/en/privacy.html')
        with open(dst, 'w', encoding='utf-8') as f:
            f.write(content)
    print("  EN done")
    
    print("Done!")

if __name__ == '__main__':
    main()