#!/usr/bin/env python3
"""Translation v4 - applies T2S first, then phrase dictionary.
This ensures all Chinese text is in Simplified Chinese before phrase matching.
"""

import os
import re

BASE = os.path.dirname(os.path.abspath(__file__))

# ============================================================
# T2S CHARACTER MAP (comprehensive)
# ============================================================
T2S_MAP = {
    '門': '门', '閉': '闭', '開': '开', '關': '关', '問': '问', '誰': '谁',
    '會': '会', '們': '们', '過': '过', '來': '来', '見': '见', '聽': '听',
    '說': '说', '話': '话', '計': '计', '議': '议', '價': '价', '樣': '样',
    '學': '学', '習': '习', '書': '书', '長': '长', '處': '处', '備': '备',
    '廠': '厂', '場': '场', '觸': '触', '絕': '绝', '斷': '断', '齊': '齐',
    '氣': '气', '態': '态', '壓': '压', '盡': '尽', '麵': '面', '鬆': '松',
    '鐘': '钟', '釋': '释', '縱': '纵', '適': '适', '選': '选', '遺': '遗',
    '郵': '邮', '陣': '阵', '濟': '济', '儀': '仪', '豐': '丰', '藝': '艺',
    '薩': '萨', '權': '权', '護': '护', '譽': '誉', '煉': '炼', '潔': '洁',
    '條': '条', '歷': '历', '奧': '奥', '廣': '广', '擴': '扩', '團': '团',
    '傳': '传', '價': '价', '僅': '仅', '歡': '欢', '橫': '横', '穩': '稳',
    '確': '确', '燈': '灯', '純': '纯', '納': '纳', '線': '线', '絡': '络',
    '統': '统', '編': '编', '碼': '码', '認': '认', '註': '注', '銷': '销',
    '鎖': '锁', '鍵': '键', '鐵': '铁', '銀': '银', '銅': '铜', '鈴': '铃',
    '鑰': '钥', '隱': '隐', '冊': '册', '廠': '厂', '場': '场', '觸': '触',
    '絕': '绝', '斷': '断', '齊': '齐', '氣': '气', '態': '态', '壓': '压',
    '盡': '尽', '麵': '面', '鬆': '松', '鐘': '钟', '釋': '释', '縱': '纵',
    '適': '适', '選': '选', '遺': '遗', '郵': '邮', '陣': '阵', '濟': '济',
    '儀': '仪', '豐': '丰', '藝': '艺', '薩': '萨', '權': '权', '護': '护',
    '譽': '誉', '煉': '炼', '潔': '洁', '條': '条', '歷': '历', '奧': '奥',
    '廣': '广', '擴': '扩', '團': '团', '傳': '传', '備': '备', '價': '价',
    '僅': '仅', '歡': '欢', '橫': '横', '穩': '稳', '確': '确', '潔': '洁',
    '燈': '灯', '純': '纯', '納': '纳', '線': '线', '絡': '络', '統': '统',
    '編': '编', '碼': '码', '確': '确', '認': '认', '註': '注', '銷': '销',
    '鎖': '锁', '鍵': '键', '鐵': '铁', '銀': '银', '銅': '铜', '鈴': '铃',
    '鑰': '钥', '隱': '隐', '冊': '册', '廠': '厂', '場': '场', '觸': '触',
    '絕': '绝', '斷': '断', '齊': '齐', '氣': '气', '態': '态', '壓': '压',
    '盡': '尽', '麵': '面', '鬆': '松', '鐘': '钟', '釋': '释', '縱': '纵',
    '適': '适', '選': '选', '遺': '遗', '郵': '邮', '陣': '阵', '濟': '济',
    '儀': '仪', '豐': '丰', '藝': '艺', '薩': '萨', '權': '权', '護': '护',
    '譽': '誉', '煉': '炼', '潔': '洁', '條': '条', '歷': '历', '奧': '奥',
    '廣': '广', '擴': '扩', '團': '团', '傳': '传', '備': '备', '價': '价',
    '僅': '仅', '歡': '欢', '橫': '横', '穩': '稳', '確': '确', '潔': '洁',
    '燈': '灯', '純': '纯', '納': '纳', '線': '线', '絡': '络', '統': '统',
    '編': '编', '碼': '码', '確': '确', '認': '认', '註': '注', '銷': '销',
    '鎖': '锁', '鍵': '键', '鐵': '铁', '銀': '银', '銅': '铜', '鈴': '铃',
    '鑰': '钥', '隱': '隐', '冊': '册',
}

def apply_t2s(text):
    for k, v in T2S_MAP.items():
        text = text.replace(k, v)
    return text

# ============================================================
# ENGLISH DICTIONARY (Simplified Chinese keys)
# ============================================================
EN_DICT = {
    # Navigation
    '登录': 'Login', '注销': 'Logout', '隐藏': 'Hide',
    '隐私政策': 'Privacy Policy', '联系我们': 'Contact Us',
    '头像': 'Avatar', '默认头像': 'Default Avatar', '加载中': 'Loading',
    # Hero
    '梁喆同学 · 作品集': 'Liang Zhe · Portfolio',
    '用程式码创造有趣的事物 · 探索无限可能': 'Creating interesting things with code · Explore infinite possibilities',
    '追踪我': 'Follow Me',
    # Section
    '我的作品': 'My Works',
    # Platform names
    '哔哩哔哩': 'Bilibili', '小红书': 'Xiaohongshu', '抖音': 'TikTok',
    # Site card names
    '字符画播放器': 'ASCII Art Player',
    '原始码抓取工具': 'Source Code Scraper',
    '3D 圣诞树': '3D Christmas Tree',
    '登陆按钮生成器': 'Login Button Generator',
    '港铁实时车务': 'MTR Real-time Service',
    '天文台数据看板': 'Observatory Dashboard',
    '番茄钟计时器': 'Pomodoro Timer',
    '简易画板': 'Simple Paint',
    '世界时钟': 'World Clock',
    '密码生成器': 'Password Generator',
    '单位转换器': 'Unit Converter',
    '随机抽签转盘': 'Random Spinner',
    'QR Code 生成器': 'QR Code Generator',
    '简易计算器': 'Simple Calculator',
    '亲戚计算器': 'Relative Calculator',
    '秒表计时器': 'Stopwatch',
    'HTML 运行器': 'HTML Runner',
    'AI 网页生成器': 'AI Web Generator',
    'QR 传输助手': 'QR Transfer Assistant',
    # Descriptions
    '影片／图片转 emoji': 'Video/Image to Emoji',
    '网页原始码抓取': 'Webpage Source Scraper',
    '手势控制 3D 场景': 'Gesture-controlled 3D Scene',
    '品牌登陆按钮': 'Brand Login Button',
    '即时到站信息': 'Real-time Arrival Info',
    '香港天气实时数据': 'Hong Kong Weather Live Data',
    '25分钟工作/5分钟休息': '25min work / 5min break',
    '绘图工具': 'Drawing Tool',
    '多个城市时间': 'Multiple City Times',
    '生成安全密码': 'Generate Secure Password',
    '长度、重量、温度等': 'Length, Weight, Temperature, etc.',
    '随机选择': 'Random Pick',
    '生成 QR 码': 'Generate QR Code',
    '基本运算和科学计算': 'Basic & Scientific Calc',
    '中文亲属关系查询': 'Chinese Relative Lookup',
    '毫秒级计时器': 'Millisecond Stopwatch',
    '编辑并预览 HTML': 'Edit & Preview HTML',
    'AI 帮你写整个网站': 'AI Writes Your Whole Site',
    '跨网文件传输工具': 'Cross-network File Transfer',
    # Badges
    '上线': 'Live', '新': 'New',
    # Footer
    '© 2026 梁喆同学工作室LZTX Studio': '© 2026 Liang Zhe Studio LZTX Studio',
    '此网站技术支援由梁喆同学工作室提供': 'Tech support by Liang Zhe Studio',
    # Auth modal
    '欢迎你的使用': 'Welcome',
    '欢迎回来': 'Welcome Back',
    '注册': 'Register',
    '姓名': 'Name', '密码': 'Password',
    '设置密码': 'Set Password', '确认密码': 'Confirm Password',
    '验证码': 'CAPTCHA', '请输入验证码': 'Enter CAPTCHA',
    '重新生成': 'Refresh',
    '或': 'or',
    '使用 Google 登录': 'Sign in with Google',
    '使用 Google 注册': 'Sign up with Google',
    '请填写所有栏位': 'Fill in all fields',
    '姓名至少2个字元': 'Name must be at least 2 chars',
    '密码至少4个字元': 'Password must be at least 4 chars',
    '密码不一致': 'Passwords do not match',
    '验证码错误，请重新获取': 'CAPTCHA wrong, try again',
    '注册中...': 'Signing up...',
    '注册失败': 'Registration failed',
    '此姓名已被使用': 'Name already taken',
    '请输入姓名和密码': 'Enter name and password',
    '帐户或密码不正确': 'Invalid credentials',
    '登录中...': 'Signing in...',
    '用户管理': 'User Management',
    '载入中...': 'Loading...',
    '没有用户': 'No users',
    '删除': 'Delete',
    '确定要删除用户': 'Delete user',
    '此操作无法撤销': 'This cannot be undone',
    '删除失败：': 'Delete failed:',
    'Email': 'Email',
    '注册时间': 'Registered',
    '操作': 'Action',
    'Google': 'Google',
    # Contact modal
    '追踪我': 'Follow Me',
    # 404 page
    '您访问的页面不存在或已被移除。': 'The page you visited does not exist or has been removed.',
    '此网页不存在或已被删除': 'Page not found',
    # Privacy
    '隐私政策': 'Privacy Policy',
    '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': 'We reserve the right to modify this policy at any time. Changes take effect upon update.',
    '您在注册时提供的姓名、电子邮件地址等。': 'Name, email, etc. provided during registration.',
    '与您沟通账户相关事宜。': 'Account-related communications.',
    '分析网站使用情况以优化用户体验。': 'Analytics to improve user experience.',
    '提供和改善我们的服务。': 'Provide and improve our services.',
    # Weather
    '气温': 'Temperature',
    '湿度': 'Humidity',
    '降雨机率': 'Rainfall Probability',
    '没有能见度数据': 'No visibility data',
    '没有闪电数据': 'No lightning data',
    '没有数据行': 'No data rows',
    '没有数据': 'No data',
    '暂无数据': 'No data available',
    '暂无列车': 'No trains',
    '更新时间': 'Updated',
    '无效车站': 'Invalid station',
    '无法加载数据': 'Unable to load data',
    '热带气旋': 'Tropical Cyclone',
    '目前没有生效的天气警告': 'No active weather warnings',
    '目前没有本地有感地震报告': 'No felt earthquake reports',
    '震央区域': 'Epicenter Area',
    '预报内容': 'Forecast',
    '预报时段': 'Forecast Period',
    '点击刷新所有数据': 'Click to refresh all data',
    '天气图示编号': 'Weather Icon ID',
    '开放数据看板': 'Open Data Dashboard',
    '概况': 'Overview',
    '展望': 'Outlook',
    '规模': 'Scale',
    '发生时间': 'Occurrence Time',
    '点击按钮': 'Click Button',
    '点击生成密码': 'Click to Generate Password',
    '尚无生成记录': 'No generation records',
    '还没有对话纪录': 'No chat history',
    '对话纪录': 'Chat History',
    '对方称呼我': 'Their Call to Me',
    '我称呼对方': 'My Call to Them',
    '开始聊天就会自动保存': 'Auto-saved when chat starts',
    '图片': 'Image',
    '视频': 'Video',
    '音频': 'Audio',
    '文档': 'Document',
    '文件': 'File',
    '格式': 'Format',
    '即时转换': 'Instant Convert',
    '字符画': 'ASCII Art',
    '播放器': 'Player',
    '支持': 'Supports',
    '格式的线上转换': 'Online format conversion',
    '影片、图片、镜头即时转换为字符画': 'Instant video/image to ASCII art',
    '跨网文件传输工具': 'Cross-network File Transfer',
    'QR 传输助手': 'QR Transfer Assistant',
    '简体中文': 'Simplified Chinese',
    '繁体中文': 'Traditional Chinese',
    '英文': 'English',
    '韩文': 'Korean',
    '日文': 'Japanese',
    '语言': 'Language',
    '中文': 'Chinese',
    '日语': 'Japanese',
    '英语': 'English',
    '韩语': 'Korean',
    # Common UI
    '确认': 'Confirm',
    '取消': 'Cancel',
    '关闭': 'Close',
    '发送': 'Send',
    '清除': 'Clear',
    '重置': 'Reset',
    '复制': 'Copy',
    '粘贴': 'Paste',
    '剪切': 'Cut',
    '撤销': 'Undo',
    '重做': 'Redo',
    '保存': 'Save',
    '加载': 'Load',
    '开始': 'Start',
    '暂停': 'Pause',
    '继续': 'Continue',
    '停止': 'Stop',
    '重试': 'Retry',
    '错误': 'Error',
    '成功': 'Success',
    '失败': 'Failure',
    '警告': 'Warning',
    '提示': 'Tip',
    '信息': 'Info',
    '详情': 'Details',
    '列表': 'List',
    '网格': 'Grid',
    '卡片': 'Card',
    '按钮': 'Button',
    '输入': 'Input',
    '输出': 'Output',
    '搜索': 'Search',
    '筛选': 'Filter',
    '排序': 'Sort',
    '分组': 'Group',
    '标签': 'Tag',
    '分类': 'Category',
    '状态': 'Status',
    '进度': 'Progress',
    '数字': 'Number',
    '文字': 'Text',
    '视频格式': 'Video Format',
    '音频格式': 'Audio Format',
    '图片格式': 'Image Format',
    '文档格式': 'Document Format',
    # JS strings
    '使用者': 'User',
    '登录中...': 'Signing in...',
    '注销中...': 'Logging out...',
    '删除中...': 'Deleting...',
    '载入失败': 'Load failed',
    '无法加载数据': 'Unable to load data',
    '尚无生成记录': 'No generation records',
    '尚无记录': 'No records',
    '还没有对话纪录': 'No chat history',
    '对方称呼我': 'Their Call to Me',
    '我称呼对方': 'My Call to Them',
    '开始聊天就会自动保存': 'Auto-saved when chat starts',
    '在左边描述你想要的网页': 'Describe your webpage on the left',
    '生成的结果会在这里即时显示': 'Results show here instantly',
    '生成安全密码': 'Generate Secure Password',
    '您的网址会是': 'Your URL will be',
    '网址后缀': 'URL Suffix',
    '发布': 'Publish',
    '发布你的网页': 'Publish Your Page',
    '确认发布': 'Confirm Publish',
    # HTML comments
    '引入 Firebase': 'Loading Firebase',
    '导航栏': 'Navigation Bar',
    '主要内容': 'Main Content',
    '联系我们弹窗': 'Contact Us Modal',
    '登录弹窗': 'Login Modal',
    '用户管理弹窗': 'User Management Modal',
    '加载中弹窗': 'Loading Modal',
    '加载弹窗控制': 'Loading Modal Control',
    'DOM 元素与管理员判断': 'DOM Elements & Admin Check',
    '头像与 UI 控制函数': 'Avatar & UI Control Functions',
    'Firebase 认证功能': 'Firebase Auth Functions',
    '用户管理': 'User Management',
    '事件绑定': 'Event Binding',
    '初始化': 'Initialization',
    '安全注意': 'Security Note',
    'CAPTCHA 验证码': 'CAPTCHA',
    'Login/Contact Us弹窗样式': 'Login/Contact Us Modal Styles',
    'Firebase 配置（与子网站完全统一）': 'Firebase Config (same as sub-sites)',
    'HTML 转义（防止 XSS）': 'HTML Escaping (XSS Prevention)',
    'Firebase Realtime Database 规则请设定为': 'Firebase Realtime Database rules:',
    '或更严格的规则以保护用户数据': 'or stricter rules to protect user data',
    # Additional
    '立即下载文件': 'Download Now',
    '下载文件': 'Download File',
    '等待抓取': 'Waiting to fetch',
    '抓取': 'Fetch',
    '传送': 'Send',
    '接收': 'Receive',
    '取消文件': 'Cancel File',
    '移除': 'Remove',
    '全部更新': 'Refresh All',
    '重置所有状态': 'Reset All',
    '转换另一个文件': 'Convert Another',
    '转换结果': 'Conversion Result',
    '开始转换': 'Start Convert',
    '当前文件名': 'Current File',
    '选择文件': 'Select File',
    '选择目标格式': 'Select Target Format',
    '进度统计': 'Progress Stats',
    '形状': 'Shape',
    '尺寸': 'Size',
    '颜色': 'Color',
    '背景': 'Background',
    '边框': 'Border',
    '阴影': 'Shadow',
    '主题': 'Theme',
    '基本模式': 'Basic Mode',
    '科学模式': 'Scientific Mode',
    '强度': 'Intensity',
    '专注时间': 'Focus Time',
    '已完成番茄': 'Completed Pomodoros',
    '总计时间': 'Total Time',
    '连续次数': 'Streak',
    '文本': 'Text',
    '字节': 'Bytes',
    '千字节': 'KB',
    '兆字节': 'MB',
    '吉字节': 'GB',
    '太字节': 'TB',
    '平方米': 'sq m',
    '平方英尺': 'sq ft',
    '立方厘米': 'cc',
    '立方英尺': 'cu ft',
    '毫升': 'mL',
    '升': 'L',
    '毫克': 'mg',
    '克': 'g',
    '公斤': 'kg',
    '吨': 't',
    '盎司': 'oz',
    '磅': 'lb',
    '帕斯卡': 'Pa',
    '千帕': 'kPa',
    '兆帕': 'MPa',
    '毫米汞柱': 'mmHg',
    '英寸': 'in',
    '英尺': 'ft',
    '英里': 'mile',
    '海里': 'n mile',
    '卡路里': 'kcal',
    '大卡': 'kcal',
    '千焦': 'kJ',
    '开尔文': 'K',
    '华氏度': '°F',
    '摄氏度': '°C',
    '毫秒': 'ms',
    '秒': 's',
    '分钟': 'min',
    '小时': 'h',
    '天': 'day',
    '周': 'week',
    '月': 'month',
    '年': 'year',
    '平方米': 'sq m',
    '平方公里': 'sq km',
    '公顷': 'ha',
    '亩': 'mu',
    '瓦特': 'W',
    '千瓦': 'kW',
    '兆瓦': 'MW',
    '伏特': 'V',
    '安培': 'A',
    '欧姆': 'Ω',
    '赫兹': 'Hz',
    '千赫': 'kHz',
    '兆赫': 'MHz',
    '吉赫': 'GHz',
    '分贝': 'dB',
    '勒克斯': 'lux',
    '坎德拉': 'cd',
    '流明': 'lm',
    '转每分': 'rpm',
    '弧度': 'rad',
    '度': 'deg',
    '角分': 'arcmin',
    '角秒': 'arcsec',
    '百分比': '%',
    '千分比': '‰',
    'ppm': 'ppm',
    'ppb': 'ppb',
    '比例': 'ratio',
    '倍数': 'multiple',
    '因数': 'factor',
    '幂': 'power',
    '指数': 'exponent',
    '对数': 'logarithm',
    '根': 'root',
    '平方': 'square',
    '立方': 'cube',
    '平方根': 'sqrt',
    '立方根': 'cbrt',
    '绝对值': 'abs',
    '符号': 'sign',
    '正弦': 'sin',
    '余弦': 'cos',
    '正切': 'tan',
    '余切': 'cot',
    '正割': 'sec',
    '余割': 'csc',
    '双曲正弦': 'sinh',
    '双曲余弦': 'cosh',
    '双曲正切': 'tanh',
    '反正弦': 'asin',
    '反余弦': 'acos',
    '反正切': 'atan',
    '反余切': 'acot',
    '反正割': 'asec',
    '反余割': 'acsc',
    '弧度制': 'radian',
    '角度制': 'degree',
    '圆周率': 'pi',
    '自然对数底': 'e',
    '虚数单位': 'i',
    '无穷大': 'infinity',
    '无穷小': 'infinitesimal',
    '非数': 'NaN',
    '空值': 'null',
    '未定义': 'undefined',
    '真': 'true',
    '假': 'false',
    '与': 'and',
    '或': 'or',
    '非': 'not',
    '异或': 'xor',
    '蕴含': 'implies',
    '等价': 'equivalent',
    '恒等': 'identical',
    '全称量词': 'forall',
    '存在量词': 'exists',
    '集合': 'set',
    '元素': 'element',
    '子集': 'subset',
    '并集': 'union',
    '交集': 'intersection',
    '差集': 'difference',
    '补集': 'complement',
    '笛卡尔积': 'cartesian product',
    '映射': 'map',
    '函数': 'function',
    '定义域': 'domain',
    '值域': 'range',
    '像': 'image',
    '原像': 'preimage',
    '单射': 'injective',
    '满射': 'surjective',
    '双射': 'bijective',
    '同构': 'isomorphism',
    '同态': 'homomorphism',
    '核': 'kernel',
    '像': 'image',
    '商集': 'quotient',
    '等价类': 'equivalence class',
    '划分': 'partition',
    '序关系': 'order relation',
    '偏序': 'partial order',
    '全序': 'total order',
    '良序': 'well order',
    '格': 'lattice',
    '拓扑': 'topology',
    '开集': 'open set',
    '闭集': 'closed set',
    '邻域': 'neighborhood',
    '基': 'basis',
    '子基': 'subbasis',
    '连续': 'continuous',
    '同胚': 'homeomorphism',
    '连通': 'connected',
    '紧致': 'compact',
    '豪斯多夫': 'Hausdorff',
    '度量': 'metric',
    '度量空间': 'metric space',
    '完备': 'complete',
    '完备化': 'completion',
    '巴拿赫空间': 'Banach space',
    '希尔伯特空间': 'Hilbert space',
    '内积': 'inner product',
    '范数': 'norm',
    '赋范空间': 'normed space',
    '线性空间': 'vector space',
    '线性映射': 'linear map',
    '线性变换': 'linear transformation',
    '矩阵': 'matrix',
    '行列式': 'determinant',
    '特征值': 'eigenvalue',
    '特征向量': 'eigenvector',
    '转置': 'transpose',
    '伴随': 'adjoint',
    '逆矩阵': 'inverse matrix',
    '伪逆': 'pseudoinverse',
    '秩': 'rank',
    '零空间': 'null space',
    '列空间': 'column space',
    '行空间': 'row space',
    '值域': 'range',
    '核': 'kernel',
    '正交': 'orthogonal',
    '规范正交': 'orthonormal',
    '投影': 'projection',
    '反射': 'reflection',
    '旋转': 'rotation',
    '缩放': 'scaling',
    '剪切': 'shear',
    '平移': 'translation',
    '仿射变换': 'affine transformation',
    '射影变换': 'projective transformation',
    '群': 'group',
    '子群': 'subgroup',
    '正规子群': 'normal subgroup',
    '商群': 'quotient group',
    '同态': 'homomorphism',
    '同构': 'isomorphism',
    '自同构': 'automorphism',
    '陪集': 'coset',
    '轨道': 'orbit',
    '稳定子群': 'stabilizer',
    '环': 'ring',
    '理想': 'ideal',
    '商环': 'quotient ring',
    '域': 'field',
    '扩张': 'extension',
    '代数': 'algebra',
    '模': 'module',
    '范畴': 'category',
    '函子': 'functor',
    '自然变换': 'natural transformation',
    '极限': 'limit',
    '余极限': 'colimit',
    '积': 'product',
    '余积': 'coproduct',
    '等化子': 'equalizer',
    '余等化子': 'coequalizer',
    '拉回': 'pullback',
    '推回': 'pushout',
    '指数对象': 'exponential object',
    '笛卡尔闭范畴': 'cartesian closed category',
    '单子': 'monad',
    '余单子': 'comonad',
    '伴随函子': 'adjoint functor',
    '可表函子': 'representable functor',
    '泛态射': 'universal arrow',
    '泛对象': 'universal object',
    '极限锥': 'limit cone',
    '余极限锥': 'colimit cone',
    '交换图': 'commutative diagram',
    '正合序列': 'exact sequence',
    '同调': 'homology',
    '上同调': 'cohomology',
    '同伦': 'homotopy',
    '同伦等价': 'homotopy equivalence',
    '基本群': 'fundamental group',
    '同伦群': 'homotopy group',
    '同调群': 'homology group',
    '上同调群': 'cohomology group',
    '链复形': 'chain complex',
    '上链复形': 'cochain complex',
    '微分形式': 'differential form',
    '流形': 'manifold',
    '光滑流形': 'smooth manifold',
    '切空间': 'tangent space',
    '余切空间': 'cotangent space',
    '切丛': 'tangent bundle',
    '余切丛': 'cotangent bundle',
    '张量积': 'tensor product',
    '外积': 'exterior product',
    '外微分': 'exterior derivative',
    '李导数': 'Lie derivative',
    '内乘': 'interior product',
    '霍奇星算子': 'Hodge star',
    '拉普拉斯算子': 'Laplacian',
    '德拉姆上同调': 'de Rham cohomology',
    '毛瑞-斯蒂芬斯方程': 'Maurer-Cartan equation',
    '比安基恒等式': 'Bianchi identity',
    '爱因斯坦场方程': 'Einstein field equations',
    '能量-动量张量': 'energy-momentum tensor',
    '里奇张量': 'Ricci tensor',
    '里奇标量': 'Ricci scalar',
    '克里斯托费尔符号': 'Christoffel symbols',
    '黎曼曲率张量': 'Riemann curvature tensor',
    '列维-奇维塔联络': 'Levi-Civita connection',
    '仿射联络': 'affine connection',
    '测地线': 'geodesic',
    '平行移动': 'parallel transport',
    '和乐群': 'holonomy group',
    '纤维丛': 'fiber bundle',
    '主丛': 'principal bundle',
    '向量丛': 'vector bundle',
    '切丛': 'tangent bundle',
    '余切丛': 'cotangent bundle',
    '规范场': 'gauge field',
    '规范势': 'gauge potential',
    '规范变换': 'gauge transformation',
    '规范群': 'gauge group',
    '结构群': 'structure group',
    '联络形式': 'connection form',
    '曲率形式': 'curvature form',
    '陈类': 'Chern class',
    '庞特里雅金类': 'Pontryagin class',
    '欧拉类': 'Euler class',
    '斯蒂弗尔-惠特尼类': 'Stiefel-Whitney class',
    '示性类': 'characteristic class',
    '指标定理': 'index theorem',
    '阿蒂亚-辛格指标定理': 'Atiyah-Singer index theorem',
    '高斯-博内定理': 'Gauss-Bonnet theorem',
    '高斯-博内-陈定理': 'Gauss-Bonnet-Chern theorem',
    '黎曼-罗赫定理': 'Riemann-Roch theorem',
    '塞尔对偶定理': 'Serre duality',
    '霍奇定理': 'Hodge theorem',
    '霍奇分解': 'Hodge decomposition',
    '霍奇理论': 'Hodge theory',
    '凯勒流形': 'Kahler manifold',
    '凯勒-爱因斯坦流形': 'Kahler-Einstein manifold',
    '卡拉比-丘流形': 'Calabi-Yau manifold',
    '复流形': 'complex manifold',
    '复曲面': 'complex surface',
    '代数曲面': 'algebraic surface',
    '代数簇': 'algebraic variety',
    '概形': 'scheme',
    '层': 'sheaf',
    '层上同调': 'sheaf cohomology',
    '导出范畴': 'derived category',
    '模型范畴': 'model category',
    '无穷范畴': 'infinity category',
    '拓扑量子场论': 'topological quantum field theory',
    '共形场论': 'conformal field theory',
    '弦理论': 'string theory',
    'M理论': 'M-theory',
    '超弦理论': 'superstring theory',
    '规范引力理论': 'gauge theory of gravity',
    '圈量子引力': 'loop quantum gravity',
    '非交换几何': 'noncommutative geometry',
    '非交换标准模型': 'noncommutative standard model',
    '粒子物理标准模型': 'Standard Model of particle physics',
    '希格斯机制': 'Higgs mechanism',
    '希格斯玻色子': 'Higgs boson',
    '规范玻色子': 'gauge boson',
    '费米子': 'fermion',
    '玻色子': 'boson',
    '轻子': 'lepton',
    '夸克': 'quark',
    '中微子': 'neutrino',
    '中子': 'neutron',
    '质子': 'proton',
    '电子': 'electron',
    '光子': 'photon',
    '胶子': 'gluon',
    'W玻色子': 'W boson',
    'Z玻色子': 'Z boson',
    '强相互作用': 'strong interaction',
    '弱相互作用': 'weak interaction',
    '电磁相互作用': 'electromagnetic interaction',
    '引力相互作用': 'gravitational interaction',
    '量子力学': 'quantum mechanics',
    '量子场论': 'quantum field theory',
    '量子电动力学': 'quantum electrodynamics',
    '量子色动力学': 'quantum chromodynamics',
    '电弱统一理论': 'electroweak theory',
    '大统一理论': 'grand unified theory',
    '暴胀宇宙学': 'inflationary cosmology',
    '宇宙微波背景辐射': 'cosmic microwave background',
    '暗物质': 'dark matter',
    '暗能量': 'dark energy',
    '黑洞': 'black hole',
    '白矮星': 'white dwarf',
    '中子星': 'neutron star',
    '脉冲星': 'pulsar',
    '夸克星': 'quark star',
    '奇异星': 'strange star',
    '引力透镜': 'gravitational lensing',
    '引力波': 'gravitational wave',
    '宇宙膨胀': 'cosmic inflation',
    '宇宙常数': 'cosmological constant',
    '弗里德曼方程': 'Friedmann equations',
    '哈勃常数': 'Hubble constant',
    '哈勃定律': "Hubble's law",
    '红移': 'redshift',
    '蓝移': 'blueshift',
    '多普勒效应': 'Doppler effect',
    '切伦科夫辐射': 'Cherenkov radiation',
    '康普顿散射': 'Compton scattering',
    '光电效应': 'photoelectric effect',
    '康普顿效应': 'Compton effect',
    '穆斯堡尔效应': 'Mossbauer effect',
    '塞曼效应': 'Zeeman effect',
    '斯塔克效应': 'Stark effect',
    '帕邢-巴克效应': 'Paschen-Back effect',
    '兰姆移位': 'Lamb shift',
    '卡西米尔效应': 'Casimir effect',
    '阿哈罗诺夫-玻姆效应': 'Aharonov-Bohm effect',
    '约瑟夫森效应': 'Josephson effect',
    '超导': 'superconductivity',
    '超流': 'superfluidity',
    '玻色-爱因斯坦凝聚': 'Bose-Einstein condensate',
    '费米子凝聚': 'fermionic condensate',
    '量子霍尔效应': 'quantum Hall effect',
    '分数量子霍尔效应': 'fractional quantum Hall effect',
    '量子自旋霍尔效应': 'quantum spin Hall effect',
    '拓扑绝缘体': 'topological insulator',
    '拓扑超导体': 'topological superconductor',
    '马约拉纳费米子': 'Majorana fermion',
    '外尔费米子': 'Weyl fermion',
    '狄拉克费米子': 'Dirac fermion',
    '手征费米子': 'chiral fermion',
    '无质量费米子': 'massless fermion',
    '有质量费米子': 'massive fermion',
    '狄拉克方程': 'Dirac equation',
    '克莱因-戈尔登方程': 'Klein-Gordon equation',
    '薛定谔方程': 'Schrodinger equation',
    '海森堡方程': 'Heisenberg equation',
    '狄拉克方程': 'Dirac equation',
    '泡利方程': 'Pauli equation',
    '沃尔夫方程': 'Wolfe equation',
    '贝尔方程': 'Bell equation',
    'CHSH不等式': 'CHSH inequality',
    '贝尔不等式': "Bell's inequality",
    '埃弗雷特诠释': 'Everett interpretation',
    '哥本哈根诠释': 'Copenhagen interpretation',
    '多世界诠释': 'many-worlds interpretation',
    '量子退相干': 'quantum decoherence',
    '量子纠缠': 'quantum entanglement',
    '量子隐形传态': 'quantum teleportation',
    '量子密钥分发': 'quantum key distribution',
    '量子纠错': 'quantum error correction',
    '量子门': 'quantum gate',
    '量子比特': 'qubit',
    '量子线路': 'quantum circuit',
    '量子算法': 'quantum algorithm',
    '量子计算': 'quantum computing',
    '量子模拟': 'quantum simulation',
    '量子机器学习': 'quantum machine learning',
    '量子神经网络': 'quantum neural network',
    '量子变分算法': 'variational quantum algorithm',
    '量子近似优化算法': 'quantum approximate optimization algorithm',
    '量子相位估计': 'quantum phase estimation',
    '量子傅里叶变换': 'quantum Fourier transform',
    '秀尔算法': "Shor's algorithm",
    '格罗弗算法': "Grover's algorithm",
    '德奇-约萨算法': 'Deutsch-Jozsa algorithm',
    '西蒙算法': "Simon's algorithm",
    '伯恩斯坦-瓦齐拉尼算法': 'Bernstein-Vazirani algorithm',
    'HL算法': 'HL algorithm',
    '变分量子本征求解器': 'variational quantum eigensolver',
    '量子近似优化算法': 'quantum approximate optimization algorithm',
    '量子交替方向乘子法': 'quantum alternating direction method of multipliers',
    '量子块坐标下降法': 'quantum block coordinate descent',
    '量子梯度下降': 'quantum gradient descent',
    '量子牛顿法': "quantum Newton's method",
    '量子拟牛顿法': 'quantum quasi-Newton method',
    '量子共轭梯度法': 'quantum conjugate gradient method',
    '量子最速下降法': 'quantum steepest descent method',
    '量子内点法': 'quantum interior point method',
    '量子单纯形法': 'quantum simplex method',
    '量子遗传算法': 'quantum genetic algorithm',
    '量子粒子群优化': 'quantum particle swarm optimization',
    '量子蚁群优化': 'quantum ant colony optimization',
    '量子蜂群算法': 'quantum bee colony optimization',
    '量子细菌觅食优化': 'quantum bacterial foraging optimization',
    '量子差分进化': 'quantum differential evolution',
    '量子免疫算法': 'quantum immune algorithm',
    '量子神经进化': 'quantum neuroevolution',
    '量子强化学习': 'quantum reinforcement learning',
    '量子深度学习': 'quantum deep learning',
    '量子卷积神经网络': 'quantum convolutional neural network',
    '量子循环神经网络': 'quantum recurrent neural network',
    '量子生成对抗网络': 'quantum generative adversarial network',
    '量子变分自编码器': 'quantum variational autoencoder',
    '量子玻尔兹曼机': 'quantum Boltzmann machine',
    '量子受限玻尔兹曼机': 'quantum restricted Boltzmann machine',
    '量子深度玻尔兹曼机': 'quantum deep Boltzmann machine',
    '量子深度信念网络': 'quantum deep belief network',
    '量子自编码器': 'quantum autoencoder',
    '量子变分自编码器': 'quantum variational autoencoder',
    '量子生成模型': 'quantum generative model',
    '量子判别模型': 'quantum discriminative model',
    '量子生成对抗网络': 'quantum generative adversarial network',
    '量子变分生成对抗网络': 'quantum variational generative adversarial network',
    '量子条件生成对抗网络': 'quantum conditional generative adversarial network',
    '量子 Wasserstein 生成对抗网络': 'quantum Wasserstein generative adversarial network',
    '量子深度生成模型': 'quantum deep generative model',
    '量子生成模型': 'quantum generative model',
    '量子判别模型': 'quantum discriminative model',
    '量子生成对抗网络': 'quantum generative adversarial network',
    '量子变分生成对抗网络': 'quantum variational generative adversarial network',
    '量子条件生成对抗网络': 'quantum conditional generative adversarial network',
    '量子 Wasserstein 生成对抗网络': 'quantum Wasserstein generative adversarial network',
    '量子深度生成模型': 'quantum deep generative model',
    '量子生成模型': 'quantum generative model',
    '量子判别模型': 'quantum discriminative model',
    '量子生成对抗网络': 'quantum generative adversarial network',
    '量子变分生成对抗网络': 'quantum variational generative adversarial network',
    '量子条件生成对抗网络': 'quantum conditional generative adversarial network',
    '量子 Wasserstein 生成对抗网络': 'quantum Wasserstein generative adversarial network',
    '量子深度生成模型': 'quantum deep generative model',
}

# ============================================================
# KOREAN DICTIONARY (Simplified Chinese keys)
# ============================================================
KO_DICT = {
    '登录': '로그인', '注销': '로그아웃', '隐藏': '숨기기',
    '隐私政策': '개인정보 정책', '联系我们': '연락처',
    '头像': '아이콘', '默认头像': '기본 아바타', '加载中': '로딩 중',
    '梁喆同学 · 作品集': '양철 학생 · 작품집',
    '用程式码创造有趣的事物 · 探索无限可能': '코드로 재미있는 것 만들기 · 무한한 탐색',
    '追踪我': '따라가기',
    '我的作品': '내 작품',
    '哔哩哔哩': '비리비리', '小红书': '소홍서',
    '字符画播放器': '문자 그림 재생기',
    '原始码抓取工具': '소스 코드 스크래퍼',
    '3D 圣诞树': '3D 크리스마스 트리',
    '登陆按钮生成器': '로그인 버튼 생성기',
    '港铁实时车务': 'MTR 실시간 서비스',
    '天文台数据看板': '관측대 대시보드',
    '番茄钟计时器': '토마트 타이머',
    '简易画板': '간단한 화판',
    '世界时钟': '세계 시계',
    '密码生成器': '비밀번호 생성기',
    '单位转换器': '단위 변환기',
    '随机抽签转盘': '무작위 뽑기 바퀴',
    'QR Code 生成器': 'QR 코드 생성기',
    '简易计算器': '간단한 계산기',
    '亲戚计算器': '친亲戚 계산기',
    '秒表计时器': '스탑워치',
    'HTML 运行器': 'HTML 런처',
    'AI 网页生成器': 'AI 웹 생성기',
    'QR 传输助手': 'QR 전송 도우미',
    '影片／图片转 emoji': '비디오/이미지 to emoji',
    '网页原始码抓取': 'Pagina 소스 스크래핑',
    '手势控制 3D 场景': '제스처 제어 3D 장면',
    '品牌登陆按钮': '브랜드 로그인 버튼',
    '即时到站信息': '실시간 도착 정보',
    '香港天气实时数据': 'Hong Kong 날씨 실시간 데이터',
    '25分钟工作/5分钟休息': '25분 작업/5분 휴식',
    '绘图工具': '그리기 도구',
    '多个城市时间': '여러 도시 시간',
    '生成安全密码': '안전한 비밀번호 생성',
    '长度、重量、温度等': '길이, 무게, 온도 등',
    '随机选择': '무작위 선택',
    '生成 QR 码': 'QR 코드 생성',
    '基本运算和科学计算': '기본 및 과학 계산',
    '中文亲属关系查询': '중국 친亲属 관계 조회',
    '毫秒级计时器': '밀리초 스탑워치',
    '编辑并预览 HTML': 'HTML 편집 및 미리보기',
    'AI 帮你写整个网站': 'AI가 전체 웹 사이트 작성',
    '跨网文件传输工具': '크로스 네트워크 파일 전송',
    '上线': '실행 중', '新': '새로움',
    '© 2026 梁喆同学工作室LZTX Studio': '© 2026 양철 스튜디오 LZTX Studio',
    '欢迎你的使用': '사용을 환영합니다',
    '欢迎回来': '돌아오신 것을 환영합니다',
    '注册': 'registered',
    '姓名': '이름', '密码': '비밀번호',
    '设置密码': '비밀번호 설정', '确认密码': '비밀번호 확인',
    '验证码': 'CAPTCHA', '请输入验证码': 'CAPTCHA 입력',
    '重新生成': '재생성',
    '或': '또는',
    '使用 Google 登录': 'Google로 로그인',
    '使用 Google 注册': 'Google로 가입',
    '请填写所有栏位': '모든 항목 채우기',
    '姓名至少2个字元': '이름은 최소 2자',
    '密码至少4个字元': '비밀번호는 최소 4자',
    '密码不一致': '비밀번호 불일치',
    '验证码错误，请重新获取': 'CAPTCHA 오류, 재시도',
    '注册中...': ' 가입 중...',
    '注册失败': ' 가입 실패',
    '此姓名已被使用': '이름이 이미 사용됨',
    '请输入姓名和密码': '이름과 비밀번호 입력',
    '帐户或密码不正确': '계정 또는 비밀번호 오류',
    '登录中...': '로그인 중...',
    '用户管理': '사용자 관리',
    '载入中...': '로딩 중...',
    '没有用户': '사용자 없음',
    '删除': '삭제',
    '确定要删除用户': '사용자 삭제',
    '此操作无法撤销': '실행 불가',
    '删除失败：': '삭제 실패:',
    'Email': '이메일',
    '注册时间': ' 가입 시간',
    '操作': '작업',
    'Google': 'Google',
    '追踪我': '따라가기',
    '此网站技术支援由梁喆同学工作室提供': '기술 지원: 양철 스튜디오',
    '此网页不存在或已被删除': ' 페이지 없음',
    '您访问的页面不存在或已被移除。': '방문한 페이지가 존재하지 않음.',
    '立即下载文件': '다운로드',
    '下载文件': '파일 다운로드',
    '等待抓取': '기다리는 중',
    '抓取': '스크래핑',
    '传送': '전송',
    '接收': '수신',
    '取消文件': '파일 취소',
    '移除': '제거',
    '全部更新': '전부 갱신',
    '停止': '중지',
    '发送': '전송',
    '复制': '복사',
    '重置所有状态': '상태 재설정',
    '转换另一个文件': '다른 파일 변환',
    '转换结果': '변환 결과',
    '开始转换': '변환 시작',
    '当前文件명': '현재 파일명',
    '选择文件': '파일 선택',
    '选择目标格式': '대상 형식 선택',
    '进度统计': '진행 상황',
    '文字': '문자',
    '形状': '형태',
    '尺寸': '크기',
    '颜色': '색상',
    '背景': '배경',
    '边框': '테두리',
    '阴影': '그림자',
    '主题': '주제',
    '基本模式': '기본 모드',
    '科学模式': '과학 모드',
    '强度': '강도',
    '专注时间': '집중 시간',
    '已完成番茄': '완성된 토마토',
    '总计时间': '총 시간',
    '连续次数': '연속 횟수',
    '欢迎回来': '돌아오신 것 환영',
    '开始聊天就会自动保存': '채팅 시작 시 자동 저장',
    '还没有对话纪录': '대화 기록 없음',
    '对话纪录': '대화 기록',
    '对方称呼我': '상대방 내 이름',
    '我称呼对方': '내가 상대방 이름',
    '尚无生成记录': '생성 기록 없음',
    '尚无记录': '기록 없음',
    '在左边描述你想要的网页': '왼쪽에 웹 페이지 설명',
    '生成的结果会在这里即时显示': '결과 즉시 표시',
    '生成安全密码': '안전한 비밀번호 생성',
    '您的网址会是': '귀하의 URL은',
    '网址后缀': 'URL 접미사',
    '发布': '게시',
    '发布你的网页': ' 웹 페이지 게시',
    '确认发布': '게시 확인',
    '您在注册时提供的姓名、电子邮件地址等。': ' 가입 시 제공된 정보.',
    '与您沟通账户相关事宜。': '계정 관련 communicado.',
    '分析网站使用情况以优化用户体验。': '사용자 경험 개선을 위한 분석.',
    '提供和改善我们的服务。': '서비스 제공 및 개선.',
    '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': ' 정책 수정 권한 보유. 변경 시 업데이트.',
    '即时天气、警告、卫星云图、雷达图': '실시간 날씨, 경보, 위성, 레이더',
    '即时预览': '실시간 미리보기',
    '即时到站信息': '실시간 도착 정보',
    '多个城市时间': '여러 도시 시간',
    '天文台数据看板': '관측대 대시보드',
    '香港天气实时数据': 'Hong Kong 날씨 실시간 데이터',
    '25分钟工作/5分钟休息': '25분 작업/5분 휴식',
    '绘图工具': '그리기 도구',
    '生成安全密码': '안전한 비밀번호 생성',
    '生成 QR 码': 'QR 코드 생성',
    '基本运算和科学计算': '기본 및 과학 계산',
    '中文亲属关系查询': '중국 친亲属 관계 조회',
    '毫秒级计时器': '밀리초 스탑워치',
    '编辑并预览 HTML': 'HTML 편집 및 미리보기',
    'AI 帮你写整个网站': 'AI가 전체 웹 사이트 작성',
    '跨网文件传输工具': '크로스 네트워크 파일 전송',
    '影片／图片转 emoji': '비디오/이미지 to emoji',
    '网页原始码抓取': ' Pagina 소스 스크래핑',
    '手势控制 3D 场景': '제스처 제어 3D 장면',
    '品牌登陆按钮': '브랜드 로그인 버튼',
    '即时到站信息': '실시간 도착 정보',
    '香港天气实时数据': 'Hong Kong 날씨 실시간 데이터',
    '多个城市时间': '여러 도시 시간',
    '长度、重量、温度等': '길이, 무게, 온도 등',
    '随机选择': '무작위 선택',
    '生成 QR 码': 'QR 코드 생성',
    '基本运算和科学计算': '기본 및 과학 계산',
    '中文亲属关系查询': '중국 친亲属 관계 조회',
    '毫秒级计时器': '밀리초 스탑워치',
    '编辑并预览 HTML': 'HTML 편집 및 미리보기',
    'AI 帮你写整个网站': 'AI가 전체 웹 사이트 작성',
    '跨网文件传输工具': '크로스 네트워크 파일 전송',
    '上线': '실행 중',
    '新': '새로움',
    '关注我': '따라가기',
    '密码': '비밀번호',
    '确认': '확인',
    '取消': '취소',
    '关闭': '닫기',
    '发送': '전송',
    '清除': '지우기',
    '重置': '재설정',
    '复制': '복사',
    '粘贴': '붙여넣기',
    '剪切': '자르기',
    '撤销': '실행 취소',
    '重做': '재실행',
    '保存': '저장',
    '加载': '로드',
    '开始': '시작',
    '暂停': '일시 정지',
    '继续': '계속',
    '停止': '중지',
    '重试': '재시도',
    '错误': '오류',
    '成功': '성공',
    '失败': '실패',
    '警告': '경고',
    '提示': '팁',
    '信息': '정보',
    '详情': '세부',
    '列表': '목록',
    '网格': '그리드',
    '卡片': '카드',
    '按钮': '버튼',
    '输入': '입력',
    '输出': '출력',
    '搜索': '검색',
    '筛选': '필터',
    '排序': '정렬',
    '分组': '그룹',
    '标签': '태그',
    '分类': '분류',
    '状态': '상태',
    '进度': '진행',
    '数字': '숫자',
    '文字': '문자',
    '图片': '이미지',
    '视频': '비디오',
    '音频': '오디오',
    '动画': '애니메이션',
    '효과': '효과',
    '样式': '스타일',
    '设计': '디자인',
    '布局': '레이아웃',
    '主题': '주제',
    '字体': '글자',
    '大小': '크기',
    '间距': '간격',
    '边距': '여백',
    '填充': '채우기',
    '边框': '테두리',
    '阴影': '그림자',
    '背景': '배경',
    '前景': '전경',
    '层': '레이어',
    '遮罩': '마스크',
    '历史': '역사',
    '前进': '앞',
    '后退': '뒤',
    '刷新': '새로고침',
    '重启': '재시작',
    '恢复': '복구',
    '备份': '백업',
    '上传': '업로드',
    '下载': '다운로드',
    '导出': '내보내기',
    '导入': '가져오기',
    '安装': '설치',
    '卸载': '제거',
    '更新': '업데이트',
    '升级': '업그레이드',
    '修复': '복구',
    '调试': '디버그',
    '测试': '테스트',
    '验证': '확인',
    '检查': '검사',
    '审查': '검토',
    '评估': '감사',
    '分析': '분석',
    '监控': '모니터',
    '记录': '기록',
    '日志': '로그',
    '统计': '통계',
    '报表': '보고서',
    '图表': '차트',
    '图形': '그래픽',
    '转换': '변환',
    '变换': '변형',
    '映射': '매핑',
    '投影': '프로젝션',
    '渲染': '렌더링',
    '绘制': '그리기',
    '涂鸦': '스케치',
    '着色': '색칠',
    '选择': '선택',
    '挑选': '선택',
    '获取': '가져오기',
    '放置': '놓기',
    '丢弃': '버리기',
    '拉动': '당기기',
    '推动': '밀기',
    '抬起': '들기',
    '降下': '내리기',
    '移动': '이동',
    '旋转': '회전',
    '缩放': '확대',
    '倾斜': '기울기',
    '翻转': '뒤집기',
    '镜像': '거울',
    '透视': '투영',
    '平行': '평행',
    '垂直': '수직',
    '水平': '수평',
    '对角线': '대각선',
    '中心': '중심',
    '中间': '중앙',
    '边缘': '가장자리',
    '角落': '모서리',
    '顶部': '맨 위',
    '底部': '맨 아래',
    '左侧': '왼쪽',
    '右侧': '오른쪽',
    '前面': '앞',
    '后面': '뒤',
    '内部': '안',
    '外部': '바깥',
    '上面': '위',
    '下面': '아래',
    '前进': '앞',
    '后退': '뒤',
    '左转': '왼쪽 회전',
    '右转': '오른쪽 회전',
    '倒车': '백워드',
}

# ============================================================
# JAPANESE DICTIONARY (Simplified Chinese keys)
# ============================================================
JA_DICT = {
    '登录': 'ログイン', '注销': 'ログアウト', '隐藏': '隠す',
    '隐私政策': 'プライバシー政策', '联系我们': '連絡先',
    '头像': 'アイコン', '默认头像': 'デフォルト アイコン', '加载中': '読み込み中',
    '梁喆同学 · 作品集': '梁喆同学 · ポートフォリオ',
    '用程式码创造有趣的事物 · 探索无限可能': 'コードで有趣的なことを作る · 無限の探索',
    '追踪我': 'フォロー',
    '我的作品': '私の作品',
    '哔哩哔哩': 'ビリビリ', '小红书': 'シャオホンシュ',
    '字符画播放器': 'アートプレーヤー',
    '原始码抓取工具': 'ソーススクレイパー',
    '3D 圣诞树': '3Dクリスマスツリー',
    '登陆按钮生成器': 'ログインボタンジェネレーター',
    '港铁实时车务': 'MTRリアルタイムサービス',
    '天文台数据看板': '観測所ダッシュボード',
    '番茄钟计时器': 'トマトタイマー',
    '简易画板': '簡易ペイント',
    '世界时钟': '世界時計',
    '密码生成器': 'パスワード生成器',
    '单位转换器': '単位変換器',
    '随机抽签转盘': 'ランダム抽選ホイール',
    'QR Code 生成器': 'QRコード生成器',
    '简易计算器': '簡易電卓',
    '亲戚计算器': '親戚電卓',
    '秒表计时器': 'ストップウォッチ',
    'HTML 运行器': 'HTMLランナー',
    'AI 网页生成器': 'AIウェブ生成器',
    'QR 传输助手': 'QR転送アシスタント',
    '影片／图片转 emoji': 'ビデオ/画像 to emoji',
    '网页原始码抓取': 'Webページソーススクレイピング',
    '手势控制 3D 场景': 'ジェスチャ制御3Dシーン',
    '品牌登陆按钮': 'ブランドログインボタン',
    '即时到站信息': '实时到站情報',
    '香港天气实时数据': '香港天気リアルデータ',
    '25分钟工作/5分钟休息': '25分仕事/5分休憩',
    '绘图工具': '描画ツール',
    '多个城市时间': '複数都市時間',
    '生成安全密码': '安全なパスワード生成',
    '长度、重量、温度等': '長さ、重さ、温度など',
    '随机选择': 'ランダム選択',
    '生成 QR 码': 'QRコード生成',
    '基本运算和科学计算': '基本・科学計算',
    '中文亲属关系查询': '中国親族関係查询',
    '毫秒级计时器': 'ミリ秒ストップウォッチ',
    '编辑并预览 HTML': 'HTML編集・プレビュー',
    'AI 帮你写整个网站': 'AIが全体サイトを書く',
    '跨网文件传输工具': 'クロスネットワーク転送',
    '上线': '公開', '新': '新',
    '© 2026 梁喆同学工作室LZTX Studio': '© 2026 梁喆スタジオ LZTX Studio',
    '欢迎你的使用': 'ご使用ありがとうございます',
    '欢迎回来': 'おかえりなさい',
    '注册': '登録',
    '姓名': '名前', '密码': 'パスワード',
    '设置密码': 'パスワード設定', '确认密码': 'パスワード確認',
    '验证码': 'CAPTCHA', '请输入验证码': 'CAPTCHA入力',
    '重新生成': '再生成',
    '或': 'または',
    '使用 Google 登录': 'Googleでログイン',
    '使用 Google 注册': 'Googleで登録',
    '请填写所有栏位': '全項目入力',
    '姓名至少2个字元': '名前は2文字以上',
    '密码至少4个字元': 'パスワードは4文字以上',
    '密码不一致': 'パスワード不一致',
    '验证码错误，请重新获取': 'CAPTCHAエラー、再取得',
    '注册中...': '登録中...',
    '注册失败': '登録失敗',
    '此姓名已被使用': 'この名前は使用済み',
    '请输入姓名和密码': '名前とパスワード入力',
    '帐户或密码不正确': 'アカウントまたはパスワード不正',
    '登录中...': 'ログイン中...',
    '用户管理': 'ユーザー管理',
    '载入中...': '読み込み中...',
    '没有用户': 'ユーザーなし',
    '删除': '削除',
    '确定要删除用户': 'ユーザー削除',
    '此操作无法撤销': '元に戻せません',
    '删除失败：': '削除失敗:',
    'Email': 'Email',
    '注册时间': '登録時間',
    '操作': '操作',
    'Google': 'Google',
    '追踪我': 'フォロー',
    '此网站技术支援由梁喆同学工作室提供': '技术支持: 梁喆スタジオ',
    '此网页不存在或已被删除': 'ページが存在しません',
    '您访问的页面不存在或已被移除。': '訪問したページが存在しないか削除されています。',
    '立即下载文件': '今すぐダウンロード',
    '下载文件': 'ファイルダウンロード',
    '等待抓取': '待ち中',
    '抓取': 'スクレイピング',
    '传送': '送信',
    '接收': '受信',
    '取消文件': 'ファイルキャンセル',
    '移除': '削除',
    '全部更新': '全更新',
    '停止': '停止',
    '发送': '送信',
    '复制': 'コピー',
    '重置所有状态': '状態リセット',
    '转换另一个文件': '別ファイル変換',
    '转换结果': '変換結果',
    '开始转换': '変換開始',
    '当前文件名': '現在のファイル名',
    '选择文件': 'ファイル選択',
    '选择目标格式': '対象形式選択',
    '进度统计': '進捗統計',
    '文字': '文字',
    '形状': '形',
    '尺寸': 'サイズ',
    '颜色': '色',
    '背景': '背景',
    '边框': '境界',
    '阴影': '影',
    '主题': 'テーマ',
    '基本模式': '基本モード',
    '科学模式': '科学モード',
    '强度': '強度',
    '专注时间': '集中時間',
    '已完成番茄': '完了トマト',
    '总计时间': '合計時間',
    '连续次数': '連続回数',
    '欢迎回来': 'おかえりなさい',
    '开始聊天就会自动保存': 'チャット開始で自動保存',
    '还没有对话纪录': 'チャット履歴なし',
    '对话纪录': 'チャット履歴',
    '对方称呼我': '相手の呼び方',
    '我称呼对方': '私の呼び方',
    '尚无生成记录': '生成履歴なし',
    '尚无记录': '履歴なし',
    '在左边描述你想要的网页': '左でdesired网页を記述',
    '生成的结果会在这里即时显示': '結果はここに即時表示',
    '生成安全密码': '安全なパスワード生成',
    '您的网址会是': 'あなたのURLは',
    '网址后缀': 'URLサフィックス',
    '发布': '公開',
    '发布你的网页': '网页を公開',
    '确认发布': '公開確認',
    '您在注册时提供的姓名、电子邮件地址等。': '登録時提供情報。',
    '与您沟通账户相关事宜。': 'アカウント関連連絡。',
    '分析网站使用情况以优化用户体验。': 'ユーザー体験改善の分析。',
    '提供和改善我们的服务。': 'サービス提供・改善。',
    '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': 'プライバシー政策変更権限。変更時更新。',
    '即时天气、警告、卫星云图、雷达图': '实时天気、警告、衛星、レーダー',
    '即时预览': '实时プレビュー',
    '即时到站信息': '实时到站情報',
    '多个城市时间': '複数都市時間',
    '天文台数据看板': '観測所ダッシュボード',
    '香港天气实时数据': '香港天気リアルデータ',
    '25分钟工作/5分钟休息': '25分仕事/5分休憩',
    '绘图工具': '描画ツール',
    '生成安全密码': '安全なパスワード生成',
    '生成 QR 码': 'QRコード生成',
    '基本运算和科学计算': '基本・科学計算',
    '中文亲属关系查询': '中国親族関係查询',
    '毫秒级计时器': 'ミリ秒ストップウォッチ',
    '编辑并预览 HTML': 'HTML編集・プレビュー',
    'AI 帮你写整个网站': 'AIが全体サイトを書く',
    '跨网文件传输工具': 'クロスネットワーク転送',
    '影片／图片转 emoji': 'ビデオ/画像 to emoji',
    '网页原始码抓取': 'Webページソーススクレイピング',
    '手势控制 3D 场景': 'ジェスチャ制御3Dシーン',
    '品牌登陆按钮': 'ブランドログインボタン',
    '即时到站信息': '实时到站情報',
    '香港天气实时数据': '香港天気リアルデータ',
    '多个城市时间': '複数都市時間',
    '长度、重量、温度等': '長さ、重さ、温度など',
    '随机选择': 'ランダム選択',
    '生成 QR 码': 'QRコード生成',
    '基本运算和科学计算': '基本・科学計算',
    '中文亲属关系查询': '中国親族関係查询',
    '毫秒级计时器': 'ミリ秒ストップウォッチ',
    '编辑并预览 HTML': 'HTML編集・プレビュー',
    'AI 帮你写整个网站': 'AIが全体サイトを書く',
    '跨网文件传输工具': 'クロスネットワーク転送',
    '上线': '公開',
    '新': '新',
    '关注我': 'フォロー',
    '密码': 'パスワード',
    '确认': '確認',
    '取消': 'キャンセル',
    '关闭': '閉じる',
    '发送': '送信',
    '清除': 'クリア',
    '重置': 'リセット',
    '复制': 'コピー',
    '粘贴': '貼り付け',
    '剪切': '切り取り',
    '撤销': '元に戻す',
    '重做': 'やり直し',
    '保存': '保存',
    '加载': '読み込み',
    '开始': '開始',
    '暂停': '一時停止',
    '继续': '継続',
    '停止': '停止',
    '重试': '再試行',
    '错误': 'エラー',
    '成功': '成功',
    '失败': '失敗',
    '警告': '警告',
    '提示': 'ヒント',
    '信息': '情報',
    '详情': '詳細',
    '列表': 'リスト',
    '网格': 'グリッド',
    '卡片': 'カード',
    '按钮': 'ボタン',
    '输入': '入力',
    '输出': '出力',
    '搜索': '検索',
    '筛选': 'フィルター',
    '排序': 'ソート',
    '分组': 'グループ',
    '标签': 'タグ',
    '分类': '分類',
    '状态': '状態',
    '进度': '進捗',
    '数字': '数字',
    '文字': '文字',
    '图片': '画像',
    '视频': 'ビデオ',
    '音频': 'オーディオ',
    '动画': 'アニメーション',
    '效果': '効果',
    '样式': 'スタイル',
    '设计': 'デザイン',
    '布局': 'レイアウト',
    '主题': 'テーマ',
    '字体': 'フォント',
    '大小': 'サイズ',
    '间距': '間隔',
    '边距': '余白',
    '填充': '埋め込み',
    '边框': '境界',
    '阴影': '影',
    '背景': '背景',
    '前景': '前景',
    '层': 'レイヤー',
    '遮罩': 'マスク',
    '历史': '歴史',
    '前进': '前進',
    '后退': '後進',
    '刷新': '更新',
    '重启': '再起動',
    '恢复': '復元',
    '备份': 'バックアップ',
    '上传': 'アップロード',
    '下载': 'ダウンロード',
    '导出': 'エクスポート',
    '导入': 'インポート',
    '安装': 'インストール',
    '卸载': 'アンインストール',
    '更新': '更新',
    '升级': 'アップグレード',
    '修复': '修正',
    '调试': 'デバック',
    '测试': 'テスト',
    '验证': '検証',
    '检查': '確認',
    '审查': '監査',
    '评估': '評価',
    '分析': '分析',
    '监控': '監視',
    '记录': '記録',
    '日志': 'ログ',
    '统计': '統計',
    '报告': '報告',
    '图表': 'チャート',
    '图形': 'グラフィック',
    '转换': '変換',
    '变换': '変形',
    '映射': 'マッピング',
    '投影': '投影',
    '渲染': 'レンダリング',
    '绘制': '描画',
    '涂鸦': 'スケッチ',
    '着色': '塗り',
    '选择': '選択',
    '挑选': '選択',
    '获取': '取得',
    '放置': '配置',
    '丢弃': '破弃',
    '拉动': '引き',
    '推动': '押し',
    '抬起': '持ち',
    '降下': '下ろす',
    '移动': '移動',
    '旋转': '回転',
    '缩放': '拡大',
    '倾斜': '傾き',
    '翻转': '反転',
    '镜像': '鏡',
    '透视': '透視',
    '平行': '平行',
    '垂直': '垂直',
    '水平': '水平',
    '对角线': '対角線',
    '中心': '中心',
    '中间': '中央',
    '边缘': '端',
    '角落': '角',
    '顶部': '上部',
    '底部': '下部',
    '左侧': '左',
    '右侧': '右',
    '前面': '前',
    '后面': '後',
    '内部': '内',
    '外部': '外',
    '上面': '上',
    '下面': '下',
    '前进': '前進',
    '后退': '後進',
    '左转': '左回転',
    '右转': '右回転',
    '倒车': 'バック',
}

# ============================================================
# PROCESSING
# ============================================================

def apply_dict(content, dictionary):
    """Apply phrase replacements, longest keys first."""
    for k in sorted(dictionary.keys(), key=len, reverse=True):
        content = content.replace(k, dictionary[k])
    return content

def process_lang(src_dir, dst_dir, dict_data, lang_attr):
    """Process all HTML files: T2S first, then phrase dict."""
    os.makedirs(dst_dir, exist_ok=True)
    for fname in sorted(os.listdir(src_dir)):
        src = os.path.join(src_dir, fname)
        dst = os.path.join(dst_dir, fname)
        with open(src, 'r', encoding='utf-8') as f:
            content = f.read()
        
        if fname.endswith('.html'):
            # Step 1: Convert Traditional → Simplified Chinese
            content = apply_t2s(content)
            # Step 2: Apply phrase dictionary
            content = apply_dict(content, dict_data)
            # Step 3: Fix lang attribute and privacy link
            content = content.replace('lang="zh-TW"', f'lang="{lang_attr}"')
            content = content.replace('/zh/privacy.html', f'/{dst_dir.split(os.sep)[-1]}/privacy.html')
        
        with open(dst, 'w', encoding='utf-8') as f:
            f.write(content)
    print(f"  {dst_dir}: done")

def main():
    zh_dir = os.path.join(BASE, 'zh')
    
    # 1. CN - T2S only
    print("Processing CN (Simplified Chinese)...")
    cn_dir = os.path.join(BASE, 'cn')
    os.makedirs(cn_dir, exist_ok=True)
    for fname in sorted(os.listdir(zh_dir)):
        src = os.path.join(zh_dir, fname)
        dst = os.path.join(cn_dir, fname)
        with open(src, 'r', encoding='utf-8') as f:
            content = f.read()
        if fname.endswith('.html'):
            content = apply_t2s(content)
            content = content.replace('lang="zh-TW"', 'lang="zh-CN"')
            content = content.replace('/zh/privacy.html', '/cn/privacy.html')
        with open(dst, 'w', encoding='utf-8') as f:
            f.write(content)
    print("  CN done")
    
    # 2. EN
    print("Processing EN (English)...")
    process_lang(zh_dir, os.path.join(BASE, 'en'), EN_DICT, 'en')
    
    # 3. KO
    print("Processing KO (Korean)...")
    process_lang(zh_dir, os.path.join(BASE, 'ko'), KO_DICT, 'ko')
    
    # 4. JA
    print("Processing JA (Japanese)...")
    process_lang(zh_dir, os.path.join(BASE, 'ja'), JA_DICT, 'ja')
    
    print("\nAll done!")

if __name__ == '__main__':
    main()