#!/usr/bin/env python3
"""Translation v3 - comprehensive phrase-level replacement for all languages.
Uses a complete dictionary covering ALL Chinese text segments found in zh/ files.
"""

import os
import re

BASE = os.path.dirname(os.path.abspath(__file__))

# ============================================================
# CHARACTER MAP: Traditional → Simplified (for CN)
# ============================================================
T2S_CHARS = {
    '門': '门', '閉': '闭', '開': '开', '關': '关', '問': '问', '誰': '谁',
    '會': '会', '們': '们', '過': '过', '來': '来', '見': '见', '聽': '听',
    '說': '说', '話': '话', '計': '计', '議': '议', '價': '价', '樣': '样',
    '學': '学', '習': '习', '書': '书', '長': '长', '處': '处', '備': '备',
    '廠': '厂', '場': '场', '觸': '触', '絕': '绝', '斷': '断', '齊': '齐',
    '氣': '气', '態': '态', '壓': '压', '盡': '尽', '麵': '面', '鬆': '松',
    '鐘': '钟', '釋': '释', '縱': '纵', '適': '适', '選': '选', '遺': '遗',
    '郵': '邮', '陣': '阵', '濟': '济', '儀': '仪', '豐': '丰', '藝': '艺',
    '薩': '萨', '權': '权', '護': '护', '譽': '誉', '煉': '炼', '潔': '洁',
    '條': '条', '歷': '历', '奧': '奥', '廣': '广', '擴': '扩', '團': '团',
    '傳': '传', '備': '备', '價': '价', '僅': '仅', '歡': '欢', '護': '护',
    '橫': '横', '穩': '稳', '確': '确', '潔': '洁', '燈': '灯', '純': '纯',
    '納': '纳', '線': '线', '絡': '络', '統': '统', '編': '编', '碼': '码',
    '確': '确', '認': '认', '註': '注', '銷': '销', '鎖': '锁', '鍵': '键',
    '鐵': '铁', '銀': '银', '銅': '铜', '鈴': '铃', '鑰': '钥', '鎖': '锁',
    '開': '开', '關': '关', '門': '门', '問': '问', '誰': '谁', '會': '会',
    '們': '们', '過': '过', '來': '来', '見': '见', '聽': '听', '說': '说',
    '話': '话', '計': '计', '議': '议', '價': '价', '樣': '样', '學': '学',
    '習': '习', '書': '书', '長': 'long', '處': '处', '備': '备', '廠': '厂',
    '場': '场', '觸': '触', '絕': '绝', '斷': '断', '齊': '齐', '氣': '气',
    '態': '态', '壓': '压', '盡': '尽', '麵': '面', '鬆': '松', '鐘': '钟',
    '釋': '释', '縱': '纵', '適': '适', '選': '选', '遺': '遗', '郵': '邮',
    '陣': '阵', '濟': '济', '儀': '仪', '豐': '丰', '藝': '艺', '薩': '萨',
    '權': '权', '護': '护', '譽': '誉', '煉': '炼', '潔': '洁', '條': '条',
    '歷': '历', '奧': '奥', '廣': '广', '擴': '扩', '團': '团', '傳': '传',
    '備': '备', '價': '价', '僅': '仅', '歡': '欢', '護': '护', '橫': '横',
    '穩': '稳', '確': '确', '潔': '洁', '燈': '灯', '純': '纯', '納': '纳',
    '線': '线', '絡': '络', '統': '统', '編': '编', '碼': '码', '確': '确',
    '認': '认', '註': '注', '銷': '销', '鎖': '锁', '鍵': '键', '鐵': '铁',
    '銀': '银', '銅': '铜', '鈴': '铃', '鑰': '钥', '鎖': 'lock', '開': 'open',
    '關': 'close', '門': 'door', '問': 'ask', '誰': 'who', '會': 'can',
    '們': '们', '過': 'past', '來': 'come', '見': 'see', '聽': 'hear',
    '說': 'speak', '話': 'word', '計': 'plan', '議': 'discuss', '價': 'price',
    '樣': 'style', '學': 'learn', '習': 'practice', '書': 'book', '長': 'long',
    '處': 'place', '備': 'prepare', '廠': 'factory', '場': 'place', '觸': 'touch',
    '絕': 'absolute', '斷': 'break', '齊': 'even', '氣': 'gas', '態': 'state',
    '壓': 'press', '盡': 'exhaust', '麵': 'noodle', '鬆': 'loose', '鐘': 'clock',
    '釋': 'explain', '縱': 'vertical', '適': 'suitable', '選': 'choose', '遺': 'lose',
    '郵': 'post', '陣': 'array', '濟': 'economy', '儀': 'ceremony', '豐': 'abundant',
    '藝': 'art', '薩': 'Sasha', '權': 'power', '護': 'protect', '譽': 'reputation',
    '煉': 'refine', '潔': 'clean', '條': 'strip', '歷': 'history', '奧': 'Olympic',
    '廣': 'wide', '擴': 'expand', '團': 'group', '傳': 'transmit', '備': 'prepare',
    '價': 'price', '僅': 'only', '歡': 'happy', '護': 'protect', '橫': 'horizontal',
    '穩': 'stable', '確': 'exact', '潔': 'clean', '燈': 'lamp', '純': 'pure',
    '納': 'accept', '線': 'line', '絡': 'network', '統': 'system', '編': 'compile',
    '碼': 'code', '確': 'exact', '認': 'recognize', '註': 'note', '銷': 'sell',
    '鎖': 'lock', '鍵': 'key', '鐵': 'iron', '銀': 'silver', '銅': 'copper',
    '鈴': 'bell', '鑰': 'key', '鎖': 'lock', '開': 'open', '關': 'close',
    '門': 'door', '問': 'ask', '誰': 'who', '會': 'can', '們': '们',
    '過': 'past', '來': 'come', '見': 'see', '聽': 'hear', '說': 'speak',
    '話': 'word', '計': 'plan', '議': 'discuss', '價': 'price', '樣': 'style',
    '學': 'learn', '習': 'practice', '書': 'book', '長': 'long', '處': 'place',
    '備': 'prepare', '廠': 'factory', '場': 'place', '觸': 'touch', '絕': 'absolute',
    '斷': 'break', '齊': 'even', '氣': 'gas', '態': 'state', '壓': 'press',
    '盡': 'exhaust', '麵': 'noodle', '鬆': 'loose', '鐘': 'clock', '釋': 'explain',
    '縱': 'vertical', '適': 'suitable', '選': 'choose', '遺': 'lose', '郵': 'post',
    '陣': 'array', '濟': 'economy', '儀': 'ceremony', '豐': 'abundant', '藝': 'art',
    '薩': 'Sasha', '權': 'power', '護': 'protect', '譽': 'reputation', '煉': 'refine',
    '潔': 'clean', '條': 'strip', '歷': 'history', '奧': 'Olympic', '廣': 'wide',
    '擴': 'expand', '團': 'group', '傳': 'transmit', '備': 'prepare', '價': 'price',
    '僅': 'only', '歡': 'happy', '護': 'protect', '橫': 'horizontal', '穩': 'stable',
    '確': 'exact', '潔': 'clean', '燈': 'lamp', '純': 'pure', '納': 'accept',
    '線': 'line', '絡': 'network', '統': 'system', '編': 'compile', '碼': 'code',
    '確': 'exact', '認': 'recognize', '註': 'note', '銷': 'sell', '鎖': 'lock',
    '鍵': 'key', '鐵': 'iron', '銀': 'silver', '銅': 'copper', '鈴': 'bell',
    '鑰': 'key', '鎖': 'lock',
}

def apply_t2s(text):
    """Apply Traditional → Simplified character mapping."""
    for k, v in T2S_CHARS.items():
        text = text.replace(k, v)
    return text

# ============================================================
# ENGLISH DICTIONARY (phrase-level)
# ============================================================
EN_PHRASES = {
    # Navigation
    '登入': 'Login', '登出': 'Logout', '隱藏': 'Hide',
    '隐私政策': 'Privacy Policy', '聯繫我們': 'Contact Us',
    '頭像': 'Avatar', '默認頭像': 'Default Avatar', '載入中': 'Loading',
    # Hero
    '梁喆同學 · 作品集': 'Liang Zhe · Portfolio',
    '用程式碼創造有趣的事物 · 探索無限可能': 'Creating interesting things with code · Explore infinite possibilities',
    '追蹤我': 'Follow Me',
    # Section
    '我的作品': 'My Works',
    # Platform names
    '嗶哩嗶哩': 'Bilibili', '小紅書': 'Xiaohongshu', '抖音': 'TikTok',
    'YouTube': 'YouTube', 'Instagram': 'Instagram', 'QQ': 'QQ',
    # Site card names
    '字符畫播放器': 'ASCII Art Player',
    '原始碼抓取工具': 'Source Code Scraper',
    '3D 聖誕樹': '3D Christmas Tree',
    '登陸按鈕生成器': 'Login Button Generator',
    '港鐵實時車務': 'MTR Real-time Service',
    '天文台數據看板': 'Observatory Dashboard',
    '番茄鐘計時器': 'Pomodoro Timer',
    '簡易畫板': 'Simple Paint',
    '世界時鐘': 'World Clock',
    '密码生成器': 'Password Generator',
    '單位轉換器': 'Unit Converter',
    '隨機抽籤轉盤': 'Random Spinner',
    'QR Code 生成器': 'QR Code Generator',
    '簡易計算機': 'Simple Calculator',
    '親戚計算機': 'Relative Calculator',
    '秒表計時器': 'Stopwatch',
    'HTML 運行器': 'HTML Runner',
    'AI 網頁生成器': 'AI Web Generator',
    'QR 传输助手': 'QR Transfer Assistant',
    # Descriptions
    '影片／圖片轉 emoji': 'Video/Image to Emoji',
    '网页原始碼抓取': 'Webpage Source Scraper',
    '手勢控制 3D 場景': 'Gesture-controlled 3D Scene',
    '品牌登陸按鈕': 'Brand Login Button',
    '即時到站資訊': 'Real-time Arrival Info',
    '香港天氣實時數據': 'Hong Kong Weather Live Data',
    '25分鐘工作/5分鐘休息': '25min work / 5min break',
    '繪圖工具': 'Drawing Tool',
    '多個城市時間': 'Multiple City Times',
    '生成安全密码': 'Generate Secure Password',
    '長度、重量、溫度等': 'Length, Weight, Temperature, etc.',
    '隨機選擇': 'Random Pick',
    '生成 QR 碼': 'Generate QR Code',
    '基本運算和科學計算': 'Basic & Scientific Calc',
    '中文親屬關係 查询': 'Chinese Relative Lookup',
    '毫秒級計時器': 'Millisecond Stopwatch',
    '編輯並預覽 HTML': 'Edit & Preview HTML',
    'AI 幫你寫整個網站': 'AI Writes Your Whole Site',
    '跨网文件传输工具': 'Cross-network File Transfer',
    # Badges
    '上線': 'Live', '新': 'New',
    # Footer
    '© 2026 梁喆同學工作室LZTX Studio': '© 2026 Liang Zhe Studio LZTX Studio',
    '此网站技术支援由梁喆同学工作室提供': 'Tech support by Liang Zhe Studio',
    # Auth modal
    '歡迎你的使用': 'Welcome',
    '歡迎回来': 'Welcome Back',
    '登录': 'Login', '註銷': 'Register',
    '姓名': 'Name', '密码': 'Password',
    '設定密码': 'Set Password', '確認密码': 'Confirm Password',
    '驗證碼': 'CAPTCHA', '請輸入驗證碼': 'Enter CAPTCHA',
    '重新生成': 'Refresh',
    '或': 'or',
    '使用 Google 登录': 'Sign in with Google',
    '使用 Google 註冊': 'Sign up with Google',
    '請填寫所有栏位': 'Fill in all fields',
    '姓名至少2个字元': 'Name must be at least 2 chars',
    '密码至少4个字元': 'Password must be at least 4 chars',
    '密码不一致': 'Passwords do not match',
    '验证码错误，请重新获取': 'CAPTCHA wrong, try again',
    '注册中...': 'Signing up...',
    '注册失败': 'Registration failed',
    '此姓名已被使用': 'Name already taken',
    '请输入姓名和密码': 'Enter name and password',
    '帐户或密码不正确': 'Invalid credentials',
    '登录中...': 'Signing in...',
    '用户管理': 'User Management',
    '载入中...': 'Loading...',
    '没有用户': 'No users',
    '删除': 'Delete',
    '确定要删除用户': 'Delete user',
    '此操作无法撤销': 'This cannot be undone',
    '删除失败：': 'Delete failed:',
    'Email': 'Email',
    '注册时间': 'Registered',
    '操作': 'Action',
    'Google': 'Google',
    # Contact modal
    '追蹤我': 'Follow Me',
    # 404 page
    '您访问的页面不存在或已被移除。': 'The page you visited does not exist or has been removed.',
    '此网页不存在或已被删除': 'Page not found',
    # Privacy
    '隐私政策': 'Privacy Policy',
    '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': 'We reserve the right to modify this policy at any time. Changes take effect upon update.',
    '您在注册时提供的姓名、电子邮件地址等。': 'Name, email, etc. provided during registration.',
    '与您沟通账户相关事宜。': 'Account-related communications.',
    '分析网站使用情况以优化用户体验。': 'Analytics to improve user experience.',
    '提供和改善我们的服务。': 'Provide and improve our services.',
    # Weather
    '氣溫': 'Temperature',
    '濕度': 'Humidity',
    '降雨機率': 'Rainfall Probability',
    '沒有能見度數據': 'No visibility data',
    '沒有閃電數據': 'No lightning data',
    '沒有數據行': 'No data rows',
    '沒有數據': 'No data',
    '暂无数据': 'No data available',
    '暂无列车': 'No trains',
    '更新時間': 'Updated',
    '無效車站': 'Invalid station',
    '無法載入數據': 'Unable to load data',
    '熱帶氣旋': 'Tropical Cyclone',
    '目前沒有生效的天氣警告': 'No active weather warnings',
    '目前沒有本地有感地震報告': 'No felt earthquake reports',
    '震央區域': 'Epicenter Area',
    '預報內容': 'Forecast',
    '預報時段': 'Forecast Period',
    '點擊刷新所有數據': 'Click to refresh all data',
    '天氣圖示編號': 'Weather Icon ID',
    '開放數據看板': 'Open Data Dashboard',
    '概況': 'Overview',
    '展望': 'Outlook',
    '規模': 'Scale',
    '發生時間': 'Occurrence Time',
    '點擊按鈕': 'Click Button',
    '點擊生成密码': 'Click to Generate Password',
    '尚無生成记录': 'No generation records',
    '還沒有對話紀錄': 'No chat history',
    '對話紀錄': 'Chat History',
    '對方稱呼我': 'Their Call to Me',
    '我稱呼對方': 'My Call to Them',
    '開始聊天就會自動保存': 'Auto-saved when chat starts',
    '圖片': 'Image',
    '視頻': 'Video',
    '音頻': 'Audio',
    '文檔': 'Document',
    '文件': 'File',
    '格式': 'Format',
    '即時轉換': 'Instant Convert',
    '字符畫': 'ASCII Art',
    '播放器': 'Player',
    '支援': 'Supports',
    '格式的線上轉換': 'Online format conversion',
    '影片、圖片、鏡頭即時轉換為字符画': 'Instant video/image to ASCII art',
    '跨网文件传输工具': 'Cross-network File Transfer',
    'QR 传输助手': 'QR Transfer Assistant',
    '简体中文': 'Simplified Chinese',
    '繁體中文': 'Traditional Chinese',
    '英文': 'English',
    '韩文': 'Korean',
    '日文': 'Japanese',
    '语言': 'Language',
    '中文': 'Chinese',
    '日本語': 'Japanese',
    '英語': 'English',
    '韩语': 'Korean',
    # Common UI text
    '確認': 'Confirm',
    '取消': 'Cancel',
    '關閉': 'Close',
    '發送': 'Send',
    '清除': 'Clear',
    '重置': 'Reset',
    '複製': 'Copy',
    '貼上': 'Paste',
    '剪下': 'Cut',
    '撤銷': 'Undo',
    '重做': 'Redo',
    '保存': 'Save',
    '加載': 'Load',
    '開始': 'Start',
    '暂停': 'Pause',
    '繼續': 'Continue',
    '停止': 'Stop',
    '重試': 'Retry',
    '错误': 'Error',
    '成功': 'Success',
    '失敗': 'Failure',
    '警告': 'Warning',
    '提示': 'Tip',
    '信息': 'Info',
    '详情': 'Details',
    '列表': 'List',
    '网格': 'Grid',
    '卡片': 'Card',
    '按鈕': 'Button',
    '輸入': 'Input',
    '輸出': 'Output',
    '搜索': 'Search',
    '篩選': 'Filter',
    '排序': 'Sort',
    '分組': 'Group',
    '標籤': 'Tag',
    '分類': 'Category',
    '狀態': 'Status',
    '進度': 'Progress',
    '數字': 'Number',
    '文字': 'Text',
    '圖片': 'Image',
    '視頻': 'Video',
    '音頻': 'Audio',
    '動畫': 'Animation',
    '效果': 'Effect',
    '樣式': 'Style',
    '設計': 'Design',
    '佈局': 'Layout',
    '主題': 'Theme',
    '字體': 'Font',
    '大小': 'Size',
    '間距': 'Spacing',
    '邊距': 'Margin',
    '填充': 'Padding',
    '邊框': 'Border',
    '陰影': 'Shadow',
    '背景': 'Background',
    '前景': 'Foreground',
    '層': 'Layer',
    '遮罩': 'Mask',
    '歷史': 'History',
    '前進': 'Forward',
    '後退': 'Backward',
    '重新整理': 'Refresh',
    '重新啟動': 'Restart',
    '恢復': 'Restore',
    '備份': 'Backup',
    '上傳': 'Upload',
    '下载': 'Download',
    '匯出': 'Export',
    '匯入': 'Import',
    '安裝': 'Install',
    '解除安裝': 'Uninstall',
    '更新': 'Update',
    '升級': 'Upgrade',
    '修復': 'Fix',
    '調試': 'Debug',
    '測試': 'Test',
    '驗證': 'Verify',
    '檢查': 'Check',
    '審查': 'Review',
    '評估': 'Evaluate',
    '分析': 'Analyze',
    '監控': 'Monitor',
    '追蹤': 'Track',
    '記錄': 'Record',
    '日誌': 'Log',
    '統計': 'Statistics',
    '報表': 'Report',
    '圖表': 'Chart',
    '圖形': 'Graphics',
    '轉換': 'Convert',
    '變換': 'Transform',
    '映射': 'Map',
    '投影': 'Project',
    '渲染': 'Render',
    '繪製': 'Draw',
    '塗鴉': 'Doodle',
    '著色': 'Color',
    '選擇': 'Select',
    '挑選': 'Pick',
    '獲取': 'Get',
    '放置': 'Place',
    '丢弃': 'Drop',
    '拉动': 'Pull',
    '推动': 'Push',
    '抬起': 'Lift',
    '降下': 'Lower',
    '移動': 'Move',
    '旋轉': 'Rotate',
    '縮放': 'Scale',
    '傾斜': 'Tilt',
    '翻轉': 'Flip',
    '鏡像': 'Mirror',
    '透視': 'Perspective',
    '平行': 'Parallel',
    '垂直': 'Perpendicular',
    '水平': 'Horizontal',
    '對角線': 'Diagonal',
    '中心': 'Center',
    '中間': 'Middle',
    '邊緣': 'Edge',
    '角落': 'Corner',
    '頂部': 'Top',
    '底部': 'Bottom',
    '左側': 'Left',
    '右側': 'Right',
    '前面': 'Front',
    '後面': 'Back',
    '內部': 'Inside',
    '外部': 'Outside',
    '上面': 'Up',
    '下面': 'Down',
    '前進': 'Forward',
    '後退': 'Backward',
    '左轉': 'Left Turn',
    '右轉': 'Right Turn',
    '倒車': 'Reverse',
    # JS strings
    '使用者': 'User',
    'Google Login中...': 'Google Login in progress...',
    'Google 登入中...': 'Google Login in progress...',
    '载入中...': 'Loading...',
    '注册中...': 'Signing up...',
    '登录中...': 'Signing in...',
    '登出中...': 'Logging out...',
    '删除中...': 'Deleting...',
    '請填寫所有栏位': 'Fill in all fields',
    '姓名至少2个字元': 'Name must be at least 2 chars',
    '密码至少4个字元': 'Password must be at least 4 chars',
    '密码不一致': 'Passwords do not match',
    '验证码错误，请重新获取': 'CAPTCHA wrong, try again',
    '注册失败': 'Registration failed',
    '此姓名已被使用': 'Name already taken',
    '请输入姓名和密码': 'Enter name and password',
    '帐户或密码不正确': 'Invalid credentials',
    '删除失败：': 'Delete failed:',
    '确定要删除用户': 'Delete user',
    '此操作无法撤销': 'This cannot be undone',
    '沒有任何用戶': 'No users',
    '載入失敗': 'Load failed',
    '無法載入數據': 'Unable to load data',
    '尚無生成记录': 'No generation records',
    '尚無记录': 'No records',
    '还没有对话纪录': 'No chat history',
    '对话纪录': 'Chat History',
    '对方称呼我': 'Their Call to Me',
    '我称呼对方': 'My Call to Them',
    '开始聊天就会自动保存': 'Auto-saved when chat starts',
    '在左边描述你想要的网页': 'Describe your webpage on the left',
    '生成的结果会在这里即时显示': 'Results show here instantly',
    '生成安全密码': 'Generate Secure Password',
    '您的网址会是': 'Your URL will be',
    '网址后缀': 'URL Suffix',
    '发布': 'Publish',
    '发布你的网页': 'Publish Your Page',
    '确认发布': 'Confirm Publish',
    # HTML comments
    '引入 Firebase': 'Loading Firebase',
    '導航欄': 'Navigation Bar',
    '主要內容': 'Main Content',
    '聯繫我們彈窗': 'Contact Us Modal',
    '登入彈窗': 'Login Modal',
    '用戶管理彈窗': 'User Management Modal',
    '加載中彈窗': 'Loading Modal',
    '加載彈窗控制': 'Loading Modal Control',
    'DOM 元素與管理員判斷': 'DOM Elements & Admin Check',
    '頭像與 UI 控制函數': 'Avatar & UI Control Functions',
    'Firebase 認證功能': 'Firebase Auth Functions',
    '用戶管理': 'User Management',
    '事件綁定': 'Event Binding',
    '聯繫我們': 'Contact Us',
    '初始化': 'Initialization',
    '安全注意': 'Security Note',
    'CAPTCHA 驗證碼': 'CAPTCHA',
    'Login/Contact Us彈窗樣式': 'Login/Contact Us Modal Styles',
    'Firebase 配置（與子網站完全統一）': 'Firebase Config (same as sub-sites)',
    '加載彈窗控制': 'Loading Modal Control',
    'DOM 元素與管理員判斷': 'DOM Elements & Admin Check',
    '頭像與 UI 控制函數': 'Avatar & UI Control Functions',
    'Firebase 認證功能': 'Firebase Auth Functions',
    '用戶管理': 'User Management',
    '事件綁定': 'Event Binding',
    '聯繫我們': 'Contact Us',
    '初始化': 'Initialization',
    '安全注意': 'Security Note',
    'CAPTCHA 驗證碼': 'CAPTCHA',
    # Additional common phrases
    '立即下载文件': 'Download Now',
    '下载文件': 'Download File',
    '等待抓取': 'Waiting to fetch',
    '抓取': 'Fetch',
    '传送': 'Send',
    '接收': 'Receive',
    '删除': 'Delete',
    '取消': 'Cancel',
    '取消文件': 'Cancel File',
    '移除': 'Remove',
    '全部更新': 'Refresh All',
    '停止': 'Stop',
    '发送': 'Send',
    '复制': 'Copy',
    '重置所有状态': 'Reset All',
    '转换另一个文件': 'Convert Another',
    '转换结果': 'Conversion Result',
    '开始转换': 'Start Convert',
    '当前文件名': 'Current File',
    '选择文件': 'Select File',
    '选择目标格式': 'Select Target Format',
    '进度统计': 'Progress Stats',
    '文字': 'Text',
    '形狀': 'Shape',
    '尺寸': 'Size',
    '颜色': 'Color',
    '背景': 'Background',
    '邊框': 'Border',
    '陰影': 'Shadow',
    '主題': 'Theme',
    '基本模式': 'Basic Mode',
    '科學模式': 'Scientific Mode',
    '強度': 'Intensity',
    '專注時間': 'Focus Time',
    '已完成番茄': 'Completed Pomodoros',
    '總計時間': 'Total Time',
    '連續次數': 'Streak',
    '歡迎回来': 'Welcome Back',
    '開始聊天就會自動保存': 'Chat auto-saved',
    '還沒有對話紀錄': 'No chat history',
    '對話紀錄': 'Chat History',
    '對方稱呼我': 'Their Call to Me',
    '我稱呼對方': 'My Call to Them',
    '尚無生成記錄': 'No records yet',
    '尚無記錄': 'No records',
    '在左邊描述你想要的网页': 'Describe your webpage on the left',
    '生成的结果會在這裡即時顯示': 'Results show here instantly',
    '生成安全密码': 'Generate Secure Password',
    '您的网址會是': 'Your URL will be',
    '网址后綴': 'URL Suffix',
    '发布': 'Publish',
    '发布你的网页': 'Publish Your Page',
    '确认发布': 'Confirm Publish',
    '您在注册时提供的姓名、电子邮件地址等。': 'Name, email etc. provided during registration.',
    '与您沟通账户相关事宜。': 'Account-related communications.',
    '分析网站使用情况以优化用户体验。': 'Analytics to improve UX.',
    '提供和改善我们的服务。': 'Provide and improve our services.',
    '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': 'We reserve the right to modify this policy. Changes take effect upon update.',
    '即時天氣、警告、衛星雲圖、雷達圖': 'Live weather, warnings, satellite, radar',
    '即時預覽': 'Live Preview',
    '即時到站資訊': 'Real-time Arrival Info',
    '多個城市時間': 'Multiple City Times',
    '天文台數據看板': 'Observatory Dashboard',
    '香港天氣實時數據': 'Hong Kong Weather Live Data',
    '25分鐘工作/5分鐘休息': '25min work / 5min break',
    '繪圖工具': 'Drawing Tool',
    '生成安全密码': 'Generate Secure Password',
    '生成 QR 碼': 'Generate QR Code',
    '基本運算和科學計算': 'Basic & Scientific Calc',
    '中文親屬關係 查询': 'Chinese Relative Lookup',
    '毫秒級計時器': 'Millisecond Stopwatch',
    '編輯並預覽 HTML': 'Edit & Preview HTML',
    'AI 幫你寫整個網站': 'AI Writes Your Whole Site',
    '跨网文件传输工具': 'Cross-network File Transfer',
    '影片／圖片轉 emoji': 'Video/Image to Emoji',
    '网页原始碼抓取': 'Webpage Source Scraper',
    '手勢控制 3D 場景': 'Gesture-controlled 3D Scene',
    '品牌登陸按鈕': 'Brand Login Button',
    '即時到站資訊': 'Real-time Arrival Info',
    '香港天氣實時數據': 'Hong Kong Weather Live Data',
    '多個城市時間': 'Multiple City Times',
    '生成安全密码': 'Generate Secure Password',
    '長度、重量、溫度等': 'Length, Weight, Temperature, etc.',
    '隨機選擇': 'Random Pick',
    '生成 QR 碼': 'Generate QR Code',
    '基本運算和科學計算': 'Basic & Scientific Calc',
    '中文親屬關係 查询': 'Chinese Relative Lookup',
    '毫秒級計時器': 'Millisecond Stopwatch',
    '編輯並預覽 HTML': 'Edit & Preview HTML',
    'AI 幫你寫整個網站': 'AI Writes Your Whole Site',
    '跨网文件传输工具': 'Cross-network File Transfer',
    '上線': 'Live',
    '新': 'New',
    '关注我': 'Follow Me',
    '密码': 'Password',
    '确认': 'Confirm',
    '取消': 'Cancel',
    '关闭': 'Close',
    '发送': 'Send',
    '清除': 'Clear',
    '重置': 'Reset',
    '复制': 'Copy',
    '粘贴': 'Paste',
    '剪切': 'Cut',
    '撤销': 'Undo',
    '重做': 'Redo',
    '保存': 'Save',
    '加载': 'Load',
    '开始': 'Start',
    '暂停': 'Pause',
    '继续': 'Continue',
    '停止': 'Stop',
    '重试': 'Retry',
    '错误': 'Error',
    '成功': 'Success',
    '失败': 'Failure',
    '警告': 'Warning',
    '提示': 'Tip',
    '信息': 'Info',
    '详情': 'Details',
    '列表': 'List',
    '网格': 'Grid',
    '卡片': 'Card',
    '按钮': 'Button',
    '输入': 'Input',
    '输出': 'Output',
    '搜索': 'Search',
    '筛选': 'Filter',
    '排序': 'Sort',
    '分组': 'Group',
    '标签': 'Tag',
    '分类': 'Category',
    '状态': 'Status',
    '进度': 'Progress',
    '数字': 'Number',
    '文字': 'Text',
    '图片': 'Image',
    '视频': 'Video',
    '音频': 'Audio',
    '动画': 'Animation',
    '效果': 'Effect',
    '样式': 'Style',
    '设计': 'Design',
    '布局': 'Layout',
    '主题': 'Theme',
    '字体': 'Font',
    '大小': 'Size',
    '间距': 'Spacing',
    '边距': 'Margin',
    '填充': 'Padding',
    '边框': 'Border',
    '阴影': 'Shadow',
    '背景': 'Background',
    '前景': 'Foreground',
    '层': 'Layer',
    '遮罩': 'Mask',
    '历史': 'History',
    '前进': 'Forward',
    '后退': 'Backward',
    '刷新': 'Refresh',
    '重启': 'Restart',
    '恢复': 'Restore',
    '备份': 'Backup',
    '上传': 'Upload',
    '下载': 'Download',
    '导出': 'Export',
    '导入': 'Import',
    '安装': 'Install',
    '卸载': 'Uninstall',
    '更新': 'Update',
    '升级': 'Upgrade',
    '修复': 'Fix',
    '调试': 'Debug',
    '测试': 'Test',
    '验证': 'Verify',
    '检查': 'Check',
    '审查': 'Review',
    '评估': 'Evaluate',
    '分析': 'Analyze',
    '监控': 'Monitor',
    '记录': 'Record',
    '日志': 'Log',
    '统计': 'Statistics',
    '报表': 'Report',
    '图表': 'Chart',
    '图形': 'Graphics',
    '转换': 'Convert',
    '变换': 'Transform',
    '映射': 'Map',
    '投影': 'Project',
    '渲染': 'Render',
    '绘制': 'Draw',
    '涂鸦': 'Doodle',
    '着色': 'Color',
    '选择': 'Select',
    '挑选': 'Pick',
    '获取': 'Get',
    '拿取': 'Take',
    '放置': 'Place',
    '丢弃': 'Drop',
    '拉动': 'Pull',
    '推动': 'Push',
    '抬起': 'Lift',
    '降下': 'Lower',
    '移动': 'Move',
    '旋转': 'Rotate',
    '缩放': 'Scale',
    '倾斜': 'Tilt',
    '翻转': 'Flip',
    '镜像': 'Mirror',
    '透视': 'Perspective',
    '平行': 'Parallel',
    '垂直': 'Perpendicular',
    '水平': 'Horizontal',
    '对角线': 'Diagonal',
    '中心': 'Center',
    '中间': 'Middle',
    '边缘': 'Edge',
    '角落': 'Corner',
    '顶部': 'Top',
    '底部': 'Bottom',
    '左侧': 'Left',
    '右侧': 'Right',
    '前面': 'Front',
    '后面': 'Back',
    '内部': 'Inside',
    '外部': 'Outside',
    '上面': 'Up',
    '下面': 'Down',
    '前进': 'Forward',
    '后退': 'Backward',
    '左转': 'Left Turn',
    '右转': 'Right Turn',
    '倒车': 'Reverse',
}

# ============================================================
# KOREAN DICTIONARY
# ============================================================
KO_PHRASES = {
    '登入': '로그인', '登出': '로그아웃', '隱藏': '숨기기',
    '隐私政策': '개인정보 정책', '聯繫我們': '연락처',
    '頭像': '아이콘', '默認頭像': '기본 아바타', '載入中': '로딩 중',
    '梁喆同學 · 作品集': '양철 학생 · 작품집',
    '用程式碼創造有趣的事物 · 探索無限possible': '코드로 재미있는 것 만들기 · 무한한 탐색',
    '追蹤我': '따라가기',
    '我的作品': '내 작품',
    '嗶哩嗶哩': '비리비리', '小紅書': '소홍서',
    '字符畫播放器': '문자 그림 재생기',
    '原始碼抓取工具': '소스 코드 스크래퍼',
    '3D 聖誕樹': '3D 크리스마스 트리',
    '登陸按鈕生成器': '로그인 버튼 생성기',
    '港鐵實時車務': 'MTR 실시간 서비스',
    '天文台數據看板': '관측대 대시보드',
    '番茄鐘計時器': '토마ト 타이머',
    '簡易畫板': '간단한 화판',
    '世界時鐘': '세계 시계',
    '密码生成器': '비밀번호 생성기',
    '單位轉換器': '단위 변환기',
    '隨機抽籤轉盤': '무작위 뽑기 바퀴',
    'QR Code 生成器': 'QR 코드 생성기',
    '簡易計算機': '간단한 계산기',
    '親戚計算機': '친亲戚 계산기',
    '秒表計時器': '스탑워치',
    'HTML 運行器': 'HTML 런처',
    'AI 網頁生成器': 'AI 웹 생성기',
    'QR 传输助手': 'QR 전송 도우미',
    '影片／圖片轉 emoji': '비디오/이미지 to emoji',
    '网页原始碼抓取': 'Pagina 소스 스크래핑',
    '手勢控制 3D 場景': '제스처 제어 3D 장면',
    '品牌登陸按鈕': '브랜드 로그인 버튼',
    '即時到站资讯': '실시간 도착 정보',
    '香港天氣實時數據': '홍 Kong 날씨 실시간 데이터',
    '25分鐘工作/5分鐘休息': '25분 작업/5분 휴식',
    '繪圖工具': '그리기 도구',
    '多個城市時間': '여러 도시 시간',
    '生成安全密码': '안전한 비밀번호 생성',
    '長度、重量、溫度等': '길이, 무게, 온도 등',
    '隨機選擇': '무작위 선택',
    '生成 QR 码': 'QR 코드 생성',
    '基本運算和科學計算': '기본 및 과학 계산',
    '中文親屬關係查询': '중국 친亲属 관계 조회',
    '毫秒級計時器': '밀리초 스탑워치',
    '編輯並預覽 HTML': 'HTML 편집 및 미리보기',
    'AI 幫你寫整個网站': 'AI가 전체 웹사이트 작성',
    '跨网文件传输工具': '크로스 네트워크 파일 전송',
    '上線': '실행 중', '新': '새로움',
    '© 2026 梁喆同學工作室LZTX Studio': '© 2026 양철 스튜디오 LZTX Studio',
    '歡迎你的使用': '사용을 환영합니다',
    '歡迎回来': '돌아오신 것을 환영합니다',
    '登录': '로그인', '註銷': 'registered',
    '姓名': '이름', '密码': '비밀번호',
    '設定密码': '비밀번호 설정', '確認密码': '비밀번호 확인',
    '驗證碼': 'CAPTCHA', '請輸入驗證碼': 'CAPTCHA 입력',
    '重新生成': '재생성',
    '或': '또는',
    '使用 Google 登录': 'Google로 로그인',
    '使用 Google 註冊': 'Google로 가입',
    '請填寫所有栏位': '모든 항목 채우기',
    '姓名至少2个字元': '이름은 최소 2자',
    '密码至少4个字元': '비밀번호는 최소 4자',
    '密码不一致': '비밀번호 불일치',
    '验证码错误，请重新获取': 'CAPTCHA 오류, 재시도',
    '注册中...': ' 가입 중...',
    '注册失败': ' 가입 실패',
    '此姓名已被使用': '이름이 이미 사용됨',
    '请输入姓名和密码': '이름과 비밀번호 입력',
    '帐户或密码不正确': '계정 또는 비밀번호 오류',
    '登录中...': '로그인 중...',
    '用户管理': '사용자 관리',
    '载入中...': '로딩 중...',
    '没有用户': '사용자 없음',
    '删除': '삭제',
    '确定要删除用户': '사용자 삭제',
    '此操作无法撤销': '실행 불가',
    '删除失败：': '삭제 실패:',
    'Email': '이메일',
    '注册时间': ' 가입 시간',
    '操作': '작업',
    'Google': 'Google',
    '追蹤我': '따라가기',
    '此网站技术支援由梁喆同学工作室提供': '기술 지원: 양철 스튜디오',
    '此网页不存在或已被删除': ' 페이지 없음',
    '您访问的页面不存在或已被移除。': '방문한 페이지가 존재하지 않음.',
    '立即下载文件': '다운로드',
    '下载文件': '파일 다운로드',
    '等待抓取': '기다리는 중',
    '抓取': '스크래핑',
    '传送': '전송',
    '接收': '수신',
    '删除': '삭제',
    '取消': '취소',
    '取消文件': '파일 취소',
    '移除': '제거',
    '全部更新': '전부 갱신',
    '停止': '중지',
    '发送': '전송',
    '复制': '복사',
    '重置所有状态': '상태 재설정',
    '转换另一个文件': '다른 파일 변환',
    '转换结果': '변환 결과',
    '开始转换': '변환 시작',
    '当前文件명': '현재 파일명',
    '选择文件': '파일 선택',
    '选择目标格式': '대상 형식 선택',
    '进度统计': '진행 상황',
    '文字': '문자',
    '形狀': '형태',
    '尺寸': '크기',
    '颜色': '색상',
    '背景': '배경',
    '边框': '테두리',
    '阴影': '그림자',
    '主题': '주제',
    '基本模式': '기본 모드',
    '科学模式': '과학 모드',
    '强度': '강도',
    '专专注时间': '집중 시간',
    '已完成番茄': '완성된 토마토',
    '总计时间': '총 시간',
    '连续次数': '연속 횟수',
    '欢迎回来': '돌아오신 것 환영',
    '开始聊天就会自动保存': '채팅 시작 시 자동 저장',
    '还没有对话纪录': '대화 기록 없음',
    '对话纪录': '대화 기록',
    '对方称呼我': '상대방 내 이름',
    '我称呼对方': '내가 상대방 이름',
    '尚无生成记录': '생성 기록 없음',
    '尚无记录': '기록 없음',
    '在左边描述你想要的网页': '왼쪽에 웹 페이지 설명',
    '生成的结果会在这里即时显示': '결과 즉시 표시',
    '生成安全密码': '안전한 비밀번호 생성',
    '您的网址会是': '귀하의 URL은',
    '网址后缀': 'URL 접미사',
    '发布': '게시',
    '发布你的网页': ' 웹 페이지 게시',
    '确认发布': '게시 확인',
    '您在注册时提供的姓名、电子邮件地址等。': ' 가입 시 제공된 정보.',
    '与您沟通账户相关事宜。': '계정 관련 communicado.',
    '分析网站使用情况以优化用户体验。': '사용자 경험 개선을 위한 분석.',
    '提供和改善我们的服务。': '서비스 제공 및 개선.',
    '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': ' 정책 수정 권한 보유. 변경 시 업데이트.',
    '即時天氣、警告、衛星雲圖、雷達圖': '실시간 날씨, 경보, 위성, 레이더',
    '即時預覽': '실시간 미리보기',
    '即時到站資訊': '실시간 도착 정보',
    '多個城市時間': '여러 도시 시간',
    '天文台數據看板': '관측대 대시보드',
    '香港天氣實時數據': 'Hong Kong 날씨 실시간 데이터',
    '25分鐘工作/5分鐘休息': '25분 작업/5분 휴식',
    '繪圖工具': '그리기 도구',
    '生成安全密码': '안전한 비밀번호 생성',
    '生成 QR 码': 'QR 코드 생성',
    '基本運算和科學計算': '기본 및 과학 계산',
    '中文親屬關係查询': '중국 친亲属 관계 조회',
    '毫秒級計時器': '밀리초 스탑워치',
    '編輯並預覽 HTML': 'HTML 편집 및 미리보기',
    'AI 幫你寫整個网站': 'AI가 전체 웹 사이트 작성',
    '跨网文件传输工具': '크로스 네트워크 파일 전송',
    '影片／圖片轉 emoji': '비디오/이미지 to emoji',
    '网页原始碼抓取': ' Pagina 소스 스크래핑',
    '手勢控制 3D 場景': '제스처 제어 3D 장면',
    '品牌登陸按鈕': '브랜드 로그인 버튼',
    '即時到站資訊': '실시간 도착 정보',
    '香港天氣實時數據': 'Hong Kong 날씨 실시간 데이터',
    '多個城市時間': '여러 도시 시간',
    '長度、重量、溫度等': '길이, 무게, 온도 등',
    '隨機選擇': '무작위 선택',
    '生成 QR 码': 'QR 코드 생성',
    '基本運算和科學計算': '기본 및 과학 계산',
    '中文親屬關係查询': '중국 친亲属 관계 조회',
    '毫秒級計時器': '밀리초 스탑워치',
    '編輯並預覽 HTML': 'HTML 편집 및 미리보기',
    'AI 幫你寫整個网站': 'AI가 전체 웹 사이트 작성',
    '跨网文件传输工具': '크로스 네트워크 파일 전송',
    '上線': '실행 중',
    '新': '새로움',
    '关注我': '따라가기',
    '密码': '비밀번호',
    '确认': '확인',
    '取消': '취소',
    '关闭': '닫기',
    '发送': '전송',
    '清除': '지우기',
    '重置': '재설정',
    '复制': '복사',
    '粘贴': '붙여넣기',
    '剪切': '자르기',
    '撤销': '실행 취소',
    '重做': '재실행',
    '保存': '저장',
    '加载': '로드',
    '开始': '시작',
    '暂停': '일시 정지',
    '继续': '계속',
    '停止': '중지',
    '重试': '재시도',
    '错误': '오류',
    '成功': '성공',
    '失败': '실패',
    '警告': '경고',
    '提示': '팁',
    '信息': '정보',
    '详情': '세부',
    '列表': '목록',
    '网格': '그리드',
    '卡片': '카드',
    '按钮': '버튼',
    '输入': '입력',
    '输出': '출력',
    '搜索': '검색',
    '筛选': '필터',
    '排序': '정렬',
    '分组': '그룹',
    '标签': '태그',
    '分类': '분류',
    '状态': '상태',
    '进度': '진행',
    '数字': '숫자',
    '文字': '문자',
    '图片': '이미지',
    '视频': '비디오',
    '音频': '오디오',
    '动画': '애니메이션',
    '效果': '효과',
    '样式': '스타일',
    '设计': '디자인',
    '布局': '레이아웃',
    '主题': '주제',
    '字体': '글자',
    '大小': '크기',
    '间距': '간격',
    '边距': '여백',
    '填充': '채우기',
    '边框': '테두리',
    '阴影': '그림자',
    '背景': '배경',
    '前景': '전경',
    '层': '레이어',
    '遮罩': '마스크',
    '历史': '역사',
    '前进': '앞',
    '后退': '뒤',
    '刷新': '새로고침',
    '重启': '재시작',
    '恢复': '복구',
    '备份': '백업',
    '上传': '업로드',
    '下载': '다운로드',
    '导出': '내보내기',
    '导入': '가져오기',
    '安装': '설치',
    '卸载': '제거',
    '更新': '업데이트',
    '升级': '업그레이드',
    '修复': '복구',
    '调试': '디버그',
    '测试': '테스트',
    '验证': '확인',
    '检查': '검사',
    '审查': '검토',
    '评估': '감사',
    '分析': '분석',
    '监控': '모니터',
    '记录': '기록',
    '日志': '로그',
    '统计': '통계',
    '报表': '보고서',
    '图表': '차트',
    '图形': '그래픽',
    '转换': '변환',
    '变换': '변형',
    '映射': '매핑',
    '投影': '프로젝션',
    '渲染': '렌더링',
    '绘制': '그리기',
    '涂鸦': '스케치',
    '着色': '색칠',
    '选择': '선택',
    '挑选': '선택',
    '获取': '가져오기',
    '放置': '놓기',
    '丢弃': '버리기',
    '拉动': '당기기',
    '推动': '밀기',
    '抬起': '들기',
    '降下': '내리기',
    '移动': '이동',
    '旋转': '회전',
    '缩放': '확대',
    '倾斜': '기울기',
    '翻转': '뒤집기',
    '镜像': '거울',
    '透视': '투영',
    '平行': '평행',
    '垂直': '수직',
    '水平': '수평',
    '对角线': '대각선',
    '中心': '중심',
    '中间': '중앙',
    '边缘': '가장자리',
    '角落': '모서리',
    '顶部': '맨 위',
    '底部': '맨 아래',
    '左侧': '왼쪽',
    '右侧': '오른쪽',
    '前面': '앞',
    '后面': '뒤',
    '内部': '안',
    '外部': '바깥',
    '上面': '위',
    '下面': '아래',
    '前进': '앞',
    '后退': '뒤',
    '左转': '왼쪽 회전',
    '右转': '오른쪽 회전',
    '倒车': '백워드',
}

# ============================================================
# JAPANESE DICTIONARY
# ============================================================
JA_PHRASES = {
    '登入': 'ログイン', '登出': 'ログアウト', '隱藏': '隠す',
    '隐私政策': 'プライバシー政策', '聯繫我們': '連絡先',
    '頭像': 'アイコン', '默認頭像': 'デフォルト アイコン', '載入中': '読み込み中',
    '梁喆同學 · 作品集': '梁喆同学 · ポートフォリオ',
    '用程式碼創造有趣的事物 · 探索無限可能': 'コードで有趣的なことを作る · 無限の探索',
    '追蹤我': 'フォロー',
    '我的作品': '私の作品',
    '嗶哩嗶哩': 'ビリビリ', '小紅書': 'シャオホンшу',
    '字符畫播放器': 'アートプレーヤー',
    '原始碼抓取工具': 'ソーススクレイパー',
    '3D 聖誕樹': '3Dクリスマスツリー',
    '登陸按鈕生成器': 'ログインボタンジェネレーター',
    '港鐵實時車務': 'MTRリアルタイムサービス',
    '天文台數據看板': '観測所ダッシュボード',
    '番茄鐘計時器': 'トマトタイマー',
    '簡易畫板': '簡易ペイント',
    '世界時鐘': '世界時計',
    '密码生成器': 'パスワード生成器',
    '單位轉換器': '単位変換器',
    '隨機抽籤轉盤': 'ランダム抽選ホイール',
    'QR Code 生成器': 'QRコード生成器',
    '簡易計算機': '簡易電卓',
    '親戚計算機': '親戚電卓',
    '秒表計時器': 'ストップウォッチ',
    'HTML 運行器': 'HTMLランナー',
    'AI 網頁生成器': 'AIウェブ生成器',
    'QR 传输助手': 'QR転送アシスタント',
    '影片／圖片轉 emoji': 'ビデオ/画像 to emoji',
    '网页原始碼抓取': 'Webページソーススクレイピング',
    '手勢控制 3D 場景': 'ジェスチャ制御3Dシーン',
    '品牌登陸按鈕': 'ブランドログインボタン',
    '即時到站情報': '实时到站情報',
    '香港天氣實時數據': '香港天気リアルデータ',
    '25分鐘工作/5分鐘休息': '25分仕事/5分休憩',
    '繪圖工具': '描画ツール',
    '多個城市時間': '複数都市時間',
    '生成安全密码': '安全なパスワード生成',
    '長度、重量、溫度等': '長さ、重さ、温度など',
    '隨機選択': 'ランダム選択',
    '生成 QR 码': 'QRコード生成',
    '基本運算和科學計算': '基本・科学計算',
    '中文親屬關係查询': '中国親族関係查询',
    '毫秒級計時器': 'ミリ秒ストップウォッチ',
    '編輯並預覽 HTML': 'HTML編集・プレビュー',
    'AI 幫你寫整個网站': 'AIが全体サイトを書く',
    '跨网文件传输工具': 'クロスネットワーク転送',
    '上線': '公開', '新': '新',
    '© 2026 梁喆同學工作室LZTX Studio': '© 2026 梁喆スタジオ LZTX Studio',
    '歡迎你的使用': 'ご使用ありがとうございます',
    '歡迎回来': 'おかえりなさい',
    '登录': 'ログイン', '註銷': '登録',
    '姓名': '名前', '密码': 'パスワード',
    '設定密码': 'パスワード設定', '確認密码': 'パスワード確認',
    '驗證碼': 'CAPTCHA', '請輸入驗證コード': 'CAPTCHA入力',
    '重新生成': '再生成',
    '或': 'または',
    '使用 Google 登录': 'Googleでログイン',
    '使用 Google 註冊': 'Googleで登録',
    '請填寫所有栏位': '全項目入力',
    '姓名至少2个字元': '名前は2文字以上',
    '密码至少4个字元': 'パスワードは4文字以上',
    '密码不一致': 'パスワード不一致',
    '验证码错误，请重新获取': 'CAPTCHAエラー、再取得',
    '注册中...': '登録中...',
    '注册失败': '登録失敗',
    '此姓名已被使用': 'この名前は使用済み',
    '请输入姓名和密码': '名前とパスワード入力',
    '帐户或密码不正确': 'アカウントまたはパスワード不正',
    '登录中...': 'ログイン中...',
    '用户管理': 'ユーザー管理',
    '载入中...': '読み込み中...',
    '没有用户': 'ユーザーなし',
    '删除': '削除',
    '确定要删除用户': 'ユーザー削除',
    '此操作无法撤销': '元に戻せません',
    '删除失败：': '削除失敗:',
    'Email': 'Email',
    '注册时间': '登録時間',
    '操作': '操作',
    'Google': 'Google',
    '追蹤我': 'フォロー',
    '此网站技术支援由梁喆同学工作室提供': '技術サポート: 梁喆スタジオ',
    '此网页不存在或已被删除': 'ページが存在しません',
    '您访问的页面不存在或已被移除。': '訪問したページが存在しないか削除されています。',
    '立即下载文件': '今すぐダウンロード',
    '下载文件': 'ファイルダウンロード',
    '等待抓取': '待ち中',
    '抓取': 'スクレイピング',
    '传送': '送信',
    '接收': '受信',
    '删除': '削除',
    '取消': 'キャンセル',
    '取消文件': 'ファイルキャンセル',
    '移除': '削除',
    '全部更新': '全更新',
    '停止': '停止',
    '发送': '送信',
    '复制': 'コピー',
    '重置所有状态': '状態リセット',
    '转换另一个文件': '別ファイル変換',
    '转换结果': '変換結果',
    '开始转换': '変換開始',
    '当前文件名': '現在のファイル名',
    '选择文件': 'ファイル選択',
    '选择目标格式': '対象形式選択',
    '进度统计': '進捗統計',
    '文字': '文字',
    '形状': '形',
    '尺寸': 'サイズ',
    '颜色': '色',
    '背景': '背景',
    '边框': '境界',
    '阴影': '影',
    '主题': 'テーマ',
    '基本模式': '基本モード',
    '科学模式': '科学モード',
    '强度': '強度',
    '专注时间': '集中時間',
    '已完成番茄': '完了トマト',
    '总计时间': '合計時間',
    '连续次数': '連続回数',
    '欢迎回来': 'おかえりなさい',
    '开始聊天就会自动保存': 'チャット開始で自動保存',
    '还没有对话纪录': 'チャット履歴なし',
    '对话纪录': 'チャット履歴',
    '对方称呼我': '相手の呼び方',
    '我称呼对方': '私の呼び方',
    '尚无生成记录': '生成履歴なし',
    '尚无记录': '履歴なし',
    '在左边描述你想要的网页': '左でdesired网页を記述',
    '生成的结果会在这里即时显示': '結果はここに即時表示',
    '生成安全密码': '安全なパスワード生成',
    '您的网址会是': 'あなたのURLは',
    '网址后缀': 'URLサフィックス',
    '发布': '公開',
    '发布你的网页': '网页を公開',
    '确认发布': '公開確認',
    '您在注册时提供的姓名、电子邮件地址等。': '登録時提供情報。',
    '与您沟通账户相关事宜。': 'アカウント関連連絡。',
    '分析网站使用情况以优化用户体验。': 'ユーザー体験改善の分析。',
    '提供和改善我们的服务。': 'サービス提供・改善。',
    '我们保留随时修改本隐私政策的权利。任何变更将在本页面更新后生效。': 'プライバシー政策変更権限。変更時更新。',
    '即時天氣、警告、衛星雲圖、雷達圖': '实时天気、警告、衛星、レーダー',
    '即時預覽': '实时プレビュー',
    '即時到站情報': '实时到站情報',
    '多城市時間': '複数都市時間',
    '天文台数据看板': '観測所ダッシュボード',
    '香港天氣實時數據': '香港天気リアルデータ',
    '25分钟工作/5分钟休息': '25分仕事/5分休憩',
    '绘图工具': '描画ツール',
    '生成安全密码': '安全なパスワード生成',
    '生成 QR 码': 'QRコード生成',
    '基本运算和科学计算': '基本・科学計算',
    '中文亲属关系查询': '中国親族関係查询',
    '毫秒级计时器': 'ミリ秒ストップウォッチ',
    '编辑并预览 HTML': 'HTML編集・プレビュー',
    'AI 帮你写整个网站': 'AIが全体サイトを書く',
    '跨网文件传输工具': 'クロスネットワーク転送',
    '影片/图片转 emoji': 'ビデオ/画像 to emoji',
    '网页源码抓取': 'Webページソーススクレイピング',
    '手势控制 3D 场景': 'ジェスチャ制御3Dシーン',
    '品牌登录按钮': 'ブランドログインボタン',
    '实时到站情報': '实时到站情報',
    '香港天氣實時數據': '香港天気リアルデータ',
    '多城市時間': '複数都市時間',
    '长度、重量、温度等': '長さ、重さ、温度など',
    '随机选择': 'ランダム選択',
    '生成 QR 码': 'QRコード生成',
    '基本运算和科学计算': '基本・科学計算',
    '中文亲属关系查询': '中国親族関係查询',
    '毫秒级计时器': 'ミリ秒ストップウォッチ',
    '编辑并预览 HTML': 'HTML編集・プレビュー',
    'AI 帮你写整个网站': 'AIが全体サイトを書く',
    '跨网文件传输工具': 'クロスネットワーク転送',
    '上線': '公開',
    '新': '新',
    '关注我': 'フォロー',
    '密码': 'パスワード',
    '确认': '確認',
    '取消': 'キャンセル',
    '关闭': '閉じる',
    '发送': '送信',
    '清除': 'クリア',
    '重置': 'リセット',
    '复制': 'コピー',
    '粘贴': '貼り付け',
    '剪切': '切り取り',
    '撤销': '元に戻す',
    '重做': 'やり直し',
    '保存': '保存',
    '加载': '読み込み',
    '开始': '開始',
    '暂停': '一時停止',
    '继续': '継続',
    '停止': '停止',
    '重试': '再試行',
    '错误': 'エラー',
    '成功': '成功',
    '失败': '失敗',
    '警告': '警告',
    '提示': 'ヒント',
    '信息': '情報',
    '详情': '詳細',
    '列表': 'リスト',
    '网格': 'グリッド',
    '卡片': 'カード',
    '按钮': 'ボタン',
    '输入': '入力',
    '输出': '出力',
    '搜索': '検索',
    '筛选': 'フィルター',
    '排序': 'ソート',
    '分组': 'グループ',
    '标签': 'タグ',
    '分类': '分類',
    '状态': '状態',
    '进度': '進捗',
    '数字': '数字',
    '文字': '文字',
    '图片': '画像',
    '视频': 'ビデオ',
    '音频': 'オーディオ',
    '动画': 'アニメーション',
    '效果': '効果',
    '样式': 'スタイル',
    '设计': 'デザイン',
    '布局': 'レイアウト',
    '主题': 'テーマ',
    '字体': 'フォント',
    '大小': 'サイズ',
    '间距': '間隔',
    '边距': '余白',
    '填充': '埋め込み',
    '边框': '境界',
    '阴影': '影',
    '背景': '背景',
    '前景': '前景',
    '层': 'レイヤー',
    '遮罩': 'マスク',
    '历史': '歴史',
    '前进': '前進',
    '后退': '後進',
    '刷新': '更新',
    '重启': '再起動',
    '恢复': '復元',
    '备份': 'バックアップ',
    '上传': 'アップロード',
    '下载': 'ダウンロード',
    '导出': 'エクスポート',
    '导入': 'インポート',
    '安装': 'インストール',
    '卸载': 'アンインストール',
    '更新': '更新',
    '升级': 'アップグレード',
    '修复': '修正',
    '调试': 'デバック',
    '测试': 'テスト',
    '验证': '検証',
    '检查': '確認',
    '审查': '監査',
    '评估': '評価',
    '分析': '分析',
    '监控': '監視',
    '记录': '記録',
    '日志': 'ログ',
    '统计': '統計',
    '報告': '報告',
    '图表': 'チャート',
    '图形': 'グラフィック',
    '转换': '変換',
    '变换': '変形',
    '映射': 'マッピング',
    '投影': '投影',
    '渲染': 'レンダリング',
    '绘制': '描画',
    '涂鸦': 'スケッチ',
    '着色': '塗り',
    '选择': '選択',
    '挑选': '選択',
    '获取': '取得',
    '放置': '配置',
    '丢弃': '破弃',
    '拉动': '引き',
    '推动': '押し',
    '抬起': '持ち',
    '降下': '下ろす',
    '移动': '移動',
    '旋转': '回転',
    '缩放': '拡大',
    '倾斜': '傾き',
    '翻转': '反転',
    '镜像': '鏡',
    '透视': '透視',
    '平行': '平行',
    '垂直': '垂直',
    '水平': '水平',
    '对角线': '対角線',
    '中心': '中心',
    '中间': '中央',
    '边缘': '端',
    '角落': '角',
    '顶部': '上部',
    '底部': '下部',
    '左侧': '左',
    '右侧': '右',
    '前面': '前',
    '后面': '後',
    '内部': '内',
    '外部': '外',
    '上面': '上',
    '下面': '下',
    '前进': '前進',
    '后退': '後進',
    '左转': '左回転',
    '右转': '右回転',
    '倒车': 'バック',
}

# ============================================================
# PROCESSING
# ============================================================

def apply_dict(content, dictionary):
    """Apply phrase replacements, longest keys first."""
    for k in sorted(dictionary.keys(), key=len, reverse=True):
        content = content.replace(k, dictionary[k])
    return content

def process_lang(src_dir, dst_dir, dict_data, lang_attr, extra_replacements=None):
    """Process all HTML files from src_dir to dst_dir."""
    os.makedirs(dst_dir, exist_ok=True)
    for fname in sorted(os.listdir(src_dir)):
        src = os.path.join(src_dir, fname)
        dst = os.path.join(dst_dir, fname)
        with open(src, 'r', encoding='utf-8') as f:
            content = f.read()
        
        if fname.endswith('.html'):
            content = apply_dict(content, dict_data)
            content = content.replace('lang="zh-TW"', f'lang="{lang_attr}"')
            content = content.replace('/zh/privacy.html', f'/{dst_dir.split(os.sep)[-1]}/privacy.html')
            if extra_replacements:
                for old, new in extra_replacements:
                    content = content.replace(old, new)
        # else: copy non-HTML as-is
        
        with open(dst, 'w', encoding='utf-8') as f:
            f.write(content)
    print(f"  {dst_dir}: done")

def main():
    zh_dir = os.path.join(BASE, 'zh')
    
    # 1. CN - Traditional → Simplified
    print("Processing CN (Simplified Chinese)...")
    cn_dir = os.path.join(BASE, 'cn')
    os.makedirs(cn_dir, exist_ok=True)
    for fname in sorted(os.listdir(zh_dir)):
        src = os.path.join(zh_dir, fname)
        dst = os.path.join(cn_dir, fname)
        with open(src, 'r', encoding='utf-8') as f:
            content = f.read()
        if fname.endswith('.html'):
            content = apply_t2s(content)
            content = content.replace('lang="zh-TW"', 'lang="zh-CN"')
            content = content.replace('/zh/privacy.html', '/cn/privacy.html')
        with open(dst, 'w', encoding='utf-8') as f:
            f.write(content)
    print("  CN done")
    
    # 2. EN
    print("Processing EN (English)...")
    process_lang(zh_dir, os.path.join(BASE, 'en'), EN_PHRASES, 'en')
    
    # 3. KO
    print("Processing KO (Korean)...")
    process_lang(zh_dir, os.path.join(BASE, 'ko'), KO_PHRASES, 'ko')
    
    # 4. JA
    print("Processing JA (Japanese)...")
    process_lang(zh_dir, os.path.join(BASE, 'ja'), JA_PHRASES, 'ja')
    
    print("\nAll done!")

if __name__ == '__main__':
    main()